[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "motulator-export"
version = "0.2.0"
dependencies = [
    "motulator>=0.8.0",
    "numpy",
]
requires-python = ">=3.12"
authors = [
    {name = "Marko Hinkkanen", email = "marko.hinkkanen@aalto.fi"}
]
description = "Export motulator drive and grid converter systems to PLECS and Simulink"
readme = "README.md"
license = "MIT"
keywords = ["control", "converter", "motor", "PLECS", "Simulink", "simulation"]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: C",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
    "pyright",
    "pip-audit",
    "pytest",
]

[project.urls]
Homepage = "https://github.com/Aalto-Electric-Drives/motulator-export"
motulator = "https://github.com/Aalto-Electric-Drives/motulator"

[tool.hatch.build.targets.wheel]
packages = ["motulator_export"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "PL"]
ignore = ["PLR2004"]  # Ignore magic value warnings
pylint = {max-args = 14}

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["motulator_export", "examples", "tests"]
exclude = ["**/__pycache__", "**/.pytest_cache"]
typeCheckingMode = "standard"
