"""
Blocks of the control systems shared by the control methods.

In the control systems, each class of motulator is a block with a mask of its
arguments, in the hierarchy of motulator. The masks of the composite classes
pass the parameters to the blocks inside them as the constructors of motulator do,
and the masks of the top-level classes refer to the variables of the model
initialization (`init_script` of the modules of the control methods), which
correspond to the motulator API. The blocks of the classes are C-Script blocks
(S-functions in Simulink), which initialize their states from their own parameters
with the C port of the control method (`Signals`).

The measurements, the feedback signals, and the references are signal vectors
(meas, fbk, and ref, defined in the C header of the control method), whose fields
are selected by Selector blocks where motulator accesses them.

This module contains the classes common to the control methods (`PWM`,
`SpeedController`, `SpeedObserver`, and `CurrentLimiter`) and the top levels
`VectorControlSystem` and `GridConverterControlSystem` with the blocks of their
methods (`get_measurement` and `modulate`) and of the monitored signals. The
classes of the control methods are in `_sm_control`, `_im_control`, and
`_grid_control`.

"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import numpy as np
from motulator.common.control._pwm import PWM
from motulator.common.utils import dead_time_error

from motulator_export.plecs._common import (
    C_DIR,
    C_GRADNET_PARAMS,
    C_PARAMS,
    C_U_DC_MIN,
    ENABLE,
    ENABLE_DESCRIPTION,
    MONITOR,
    ControlBlock,
    MaskParam,
    _c_define,
    _fmt_mask,
    block_enable_code,
    monitored_code,
)
from motulator_export.plecs._netlist import (
    CBlock,
    Mask,
    Param,
    Port,
    Selector,
    Subsystem,
    Tag,
)
from motulator_export.plecs._schematic import _fmt

HEADER = (
    "/* Generated by motulator_export: a block of the control system. The\n"
    " * parameters come from its mask. */\n"
)


# %%
# C code helpers
def _read(port: int, width: str, var: str) -> str:
    """C code reading an input into an array."""
    return (
        f"double {var}[{width}];\n"
        f"for (int k = 0; k < {width}; k++) {{\n"
        f"    {var}[k] = InputSignal({port}, k);\n"
        "}\n"
    )


def _write(port: int, width: str, var: str) -> str:
    """C code writing an array to an output."""
    return (
        f"for (int k = 0; k < {width}; k++) {{\n"
        f"    OutputSignal({port}, k) = {var}[k];\n"
        "}\n"
    )


def complex_in(port: int) -> str:
    """Complex input."""
    return f"complex_from(InputSignal({port}, 0), InputSignal({port}, 1))"


def complex_out(port: int, value: str) -> str:
    """C code writing a complex variable to an output."""
    return (
        f"OutputSignal({port}, 0) = creal({value});\n"
        f"OutputSignal({port}, 1) = cimag({value});\n"
    )


def checks(params: list[str], required: list[str]) -> str:
    """C code checking that the required parameters are scalars."""
    return "".join(
        f"if (PDIM({params.index(p)}) != 1) {{\n"
        f'    SetErrorMessage("{p} must be a scalar.");\n'
        "    return;\n"
        "}\n"
        for p in required
    )


def mask_params(mask: Mask, expanded: dict[str, list[str]] | None = None) -> list[str]:
    """
    Parameters of a C block from its mask: the mask variables, those in `expanded`
    (e.g., the machine model par) replaced by the variables of the mask
    initialization (e.g., its fields), at the end.
    """
    expanded = expanded or {}
    names = [p.variable for p in mask.params if p.variable not in expanded]
    return names + [n for p in mask.params for n in expanded.get(p.variable, [])]


@dataclass(frozen=True)
class Signals:
    """
    C port of a control method for its blocks: the included C files, the headers
    defining the signal vectors (e.g., MEAS_WIDTH and MEAS_u_dc of the measurements
    meas), the C types and the function prefixes of the vectors (e.g., Measurements
    and measurements for measurements_pack and measurements_unpack, and optionally
    the prefix of the macros, by default the name of the vector in upper case), and
    the prefix of the names of the S-functions.
    """

    sources: tuple[str, ...]  # C files, e.g., ("common.c", "sm_flux_vector.c")
    headers: tuple[str, ...]  # e.g., ("sm_flux_vector.h",)
    vectors: dict[str, tuple[str, ...]]  # Vector -> (C type, function prefix[, macro])
    prefix: str  # e.g., "sfun_fvc"

    def macro(self, vector: str) -> str:
        """Prefix of the macros of a signal vector, e.g., "MEAS"."""
        v = self.vectors[vector]
        return v[2] if len(v) > 2 else vector.upper()

    def _define(self, name: str) -> int:
        """Value of a macro of the signal vectors."""
        for header in self.headers:
            try:
                return _c_define(header, name)
            except RuntimeError:
                pass
        raise RuntimeError(f"{name} not found in {self.headers}")

    def width(self, vector: str) -> int:
        """Width of a signal vector, e.g., "meas"."""
        return self._define(f"{self.macro(vector)}_WIDTH")

    def index(self, vector: str, name: str) -> int:
        """Index of a field of a signal vector."""
        return self._define(f"{self.macro(vector)}_{name}")

    def port(self, vector: str) -> Port:
        """Port of a signal vector."""
        return Port(vector, self.width(vector))

    def selector(self, vector: str, name: str, complex_: bool = False) -> Selector:
        """Selector of a field of a signal vector, e.g., "fbk.w_M"."""
        k = self.index(vector, name)
        indices = [k, k + 1] if complex_ else [k]
        return Selector(f"{vector}.{name}", self.width(vector), indices)

    def read(self, port: int, vector: str, declare: bool = True) -> str:
        """C code reading a signal vector from an input into the variable `vector`."""
        typ, fn = self.vectors[vector][:2]
        width = f"{self.macro(vector)}_WIDTH"
        return (
            _read(port, width, f"{vector}_u")
            + (f"{typ} {vector};\n" if declare else "")
            + f"{fn}_unpack({vector}_u, &{vector});\n"
        )

    def write(self, port: int, vector: str, var: str) -> str:
        """C code writing the variable `var` as a signal vector to an output."""
        width = f"{self.macro(vector)}_WIDTH"
        return (
            f"double y[{width}];\n"
            f"{self.vectors[vector][1]}_pack(&{var}, y);\n" + _write(port, width, "y")
        )

    def sfunction(self, name: str) -> str:
        """Name of the S-function of a block."""
        return f"{self.prefix}_{name}"

    def declarations(self, workspace: str = "") -> str:
        """Declarations of the C code of a block."""
        includes = "".join(f'#include "{C_DIR}/{f}"\n' for f in self.sources)
        gradnet = "\n" + C_GRADNET_PARAMS if "gradnet.c" in self.sources else ""
        return HEADER + includes + "\n" + C_PARAMS + gradnet + "\n" + workspace

    def class_code(
        self,
        cls: str,
        start: str,
        output: str,
        update: str = "",
        workspace: str = "",
        outputs: tuple[int, ...] = (1,),
        disabled: float | None = 0.0,
    ) -> dict[str, str]:
        """
        Code sections of the block of a class: its state `self` of the type `cls` is
        initialized by `start` from the parameters, which are read only there (the
        parameters used later are copied to the `workspace` variables). The input
        `enable` is added unless `disabled` is None.
        """
        code = {
            "Declarations": self.declarations(f"static {cls} self;\n" + workspace),
            "StartFcn": start,
            "OutputFcn": output,
            "UpdateFcn": update,
        }
        if disabled is None:
            return code
        state = [(cls, "self")] if update else []
        return block_enable_code(code, state, list(outputs), disabled)

    def function_code(
        self, output: str, start: str = "", workspace: str = ""
    ) -> dict[str, str]:
        """Code sections of the block of a function (without a state)."""
        return {
            "Declarations": self.declarations(workspace),
            "StartFcn": start,
            "OutputFcn": output,
        }


# %%
# Blocks of the common classes
T_S = Param("T_s", "T_s: Sampling period (s)", "T_s")
SAMPLING = "static double T_s; /* Sampling period */\n"


def speed_controller(sig: Signals) -> CBlock:
    """Speed controller (SpeedController)."""
    mask = Mask(
        "SpeedController (motulator)",
        "2DOF PI speed controller (SpeedController). The inputs are the speed "
        "estimate fbk.w_M, the limited torque reference ref.tau_M (anti-windup), and "
        "the speed reference w_M_ref, and the output is the torque reference.",
        [
            Param("J", "J: Total inertia (kgm²)", "speed_ctrl.J"),
            Param(
                "alpha_s",
                "alpha_s: Reference-tracking bandwidth (rad/s)",
                "speed_ctrl.alpha_s",
            ),
            Param(
                "alpha_i",
                "alpha_i: Integral-action bandwidth (rad/s), [] = alpha_s",
                "speed_ctrl.alpha_i",
            ),
            Param(
                "tau_M_max",
                "tau_M_max: Maximum motor torque (Nm)",
                "speed_ctrl.tau_M_max",
            ),
            T_S,
        ],
    )
    params = mask_params(mask)
    i = {p: k for k, p in enumerate(params)}
    start = (
        checks(params, ["J", "alpha_s", "T_s"]) + f"T_s = P({i['T_s']}, 0);\n"
        f"self = speed_controller(P({i['J']}, 0), P({i['alpha_s']}, 0), "
        f"PARAM({i['alpha_i']}),\n"
        f"                        PDIM({i['tau_M_max']}) > 0 ? P({i['tau_M_max']}, 0)"
        " : INFINITY);\n"
    )
    output = (
        "/* Torque reference */\n"
        "OutputSignal(0, 0) = pi_compute_output(&self, InputSignal(3, 0), "
        "InputSignal(1, 0), 0.0);\n"
    )
    update = (
        "/* The limited torque reference ref.tau_M (anti-windup) */\n"
        "pi_update(&self, T_s, InputSignal(2, 0));\n"
    )
    return CBlock(
        "SpeedController",
        [Port(ENABLE, 1), Port("w_M", 1), Port("tau_M", 1), Port("w_M_ref", 1)],
        [Port("tau_M_ref", 1)],
        sig.class_code("PIController", start, output, update, SAMPLING),
        params,
        sig.sfunction("speed_controller"),
        feedthrough=[1, 1, 0, 1],
        mask=mask,
    )


def pwm(sig: Signals) -> Subsystem:
    """PWM: the duty ratios (compute_output) and the realized voltage."""
    mask = Mask(
        "PWM (motulator)",
        "Space-vector PWM with the minimum-phase-error (MPE) or the minimum-magnitude-"
        "error (MME) overmodulation (PWM), with the duty-ratio error model d_err = "
        "dead_time_error(i_abc, d_abc, t_d, T_s, sign) and its compensation, and the "
        "minimum pulses. The blocks inside are "
        "its methods compute_output and get_realized_voltage.",
        [
            T_S,
            Param(
                "t_d",
                "t_d: Dead time (s) in d_err = dead_time_error(i_abc, d_abc, t_d, T_s),"
                " 0 = None",
                "pwm.t_d",
            ),
            Param(
                "i_0",
                "i_0: Current scale (A) of sign = tanh(i/i_0) in dead_time_error, "
                "0 = np.sign",
                "pwm.i_0",
            ),
            Param(
                "feedforward",
                "feedforward: Compensate for d_err (1) or not (0)",
                "pwm.feedforward",
            ),
            Param(
                "d_min",
                "d_min: Minimum duty ratio of a switching leg, 0 = no limit",
                "pwm.d_min",
            ),
            Param(
                "overmodulation",
                "overmodulation: Overmodulation, 'MPE' or 'MME'",
                "pwm.overmodulation",
            ),
        ],
        init="% MME overmodulation, or MPE\nmme = strcmp(overmodulation, 'MME');\n",
    )
    params = mask_params(mask, {"overmodulation": ["mme"]})
    start = (
        checks(params, params) + "pwm_init(&self, 1.5);\n"
        "pwm_set_overmodulation(&self, (int)P(5, 0));\n"
        "pwm_set_dead_time(&self, P(1, 0), P(0, 0), P(2, 0), (int)P(3, 0));\n"
        "pwm_set_min_pulse(&self, P(4, 0));\n"
    )
    meas = sig.port("meas")
    output = (
        sig.read(1, "meas") + "double d_abc[3];\n"
        "pwm_compute_output(&self, T_s, " + complex_in(2) + ", meas.u_dc,\n"
        "                   InputSignal(3, 0), meas.i_c_ab, d_abc);\n"
        + _write(0, "3", "d_abc")
    )
    compute = CBlock(
        "compute_output",
        [Port(ENABLE, 1), meas, Port("u_c_ref_ab", 2), Port("w", 1)],
        [Port("d_abc", 3)],
        sig.class_code(
            "PWM", start + "T_s = P(0, 0);\n", output, "", SAMPLING, (3,), 0.5
        ),
        params,
        sig.sfunction("pwm"),
    )
    output = (
        sig.read(1, "meas")
        + "/* Average of the previous and the ongoing periods, and of the\n"
        " * ongoing period */\n"
        "double complex u_c_ab =\n"
        "    pwm_realized_voltage(&self, meas.i_c_ab, meas.u_dc, 1);\n"
        "double complex u_c_zoh_ab =\n"
        "    pwm_realized_voltage(&self, meas.i_c_ab, meas.u_dc, 0);\n"
        + complex_out(0, "u_c_ab")
        + complex_out(1, "u_c_zoh_ab")
    )
    update = (
        "/* The duty ratios of the next period */\n"
        + _read(2, "3", "d_abc")
        + "pwm_update(&self, d_abc);\n"
    )
    realized = CBlock(
        "get_realized_voltage",
        [Port(ENABLE, 1), meas, Port("d_abc", 3)],
        [Port("u_c_ab", 2), Port("u_c_zoh_ab", 2)],
        sig.class_code("PWM", start, output, update, outputs=(2, 2)),
        params,
        sig.sfunction("pwm_realized_voltage"),
        feedthrough=[1, 1, 0],
    )
    return Subsystem(
        "PWM",
        [Port(ENABLE, 1), meas, Port("u_c_ref_ab", 2), Port("w", 1)],
        [Port("u_c_ab", 2), Port("u_c_zoh_ab", 2), Port("d_abc", 3)],
        [compute, realized],
        [
            (ENABLE, "compute_output:enable"),
            (ENABLE, "get_realized_voltage:enable"),
            ("meas", "compute_output:meas"),
            ("meas", "get_realized_voltage:meas"),
            ("u_c_ref_ab", "compute_output:u_c_ref_ab"),
            ("w", "compute_output:w"),
            ("compute_output:d_abc", "d_abc"),
            ("compute_output:d_abc", "get_realized_voltage:d_abc"),
            ("get_realized_voltage:u_c_ab", "u_c_ab"),
            ("get_realized_voltage:u_c_zoh_ab", "u_c_zoh_ab"),
        ],
        columns=[
            ["meas", "u_c_ref_ab", "w", ENABLE],
            ["compute_output"],
            ["get_realized_voltage"],
            ["u_c_ab", "u_c_zoh_ab", "d_abc"],
        ],
        align={
            "get_realized_voltage:d_abc": "compute_output:d_abc-1",
            "meas": "get_realized_voltage:meas",
            "u_c_ab": "get_realized_voltage:u_c_ab",
            "d_abc": "compute_output:d_abc",
        },
        tags=[ENABLE],
        mask=mask,
    )


def speed_observer(sig: Signals) -> CBlock:
    """Speed observer (SpeedObserver)."""
    mask = Mask(
        "SpeedObserver (motulator)",
        "Speed observer (SpeedObserver), driven by the speed error signal eps and the "
        "torque estimate tau_M. The mechanical system model is used if J is given.",
        [
            Param("k_w", "k_w: Speed estimation gain", "k_w"),
            Param("k_tau", "k_tau: Load torque estimation gain", "k_tau"),
            Param("J", "J: Inertia (kgm²), [] = the model not used", "J"),
            T_S,
        ],
    )
    params = mask_params(mask)
    start = (
        checks(params, ["k_w", "k_tau", "T_s"])
        + "speed_observer_init(&self, P(0, 0), P(1, 0), PDIM(2) > 0 ? P(2, 0) : 0.0);\n"
        "T_s = P(3, 0);\n"
    )
    return CBlock(
        "SpeedObserver",
        [Port(ENABLE, 1), Port("eps", 1), Port("tau_M", 1)],
        [Port("w_M", 1), Port("tau_L", 1)],
        sig.class_code(
            "SpeedObserver",
            start,
            "OutputSignal(0, 0) = self.w_M;\nOutputSignal(1, 0) = self.tau_L;\n",
            "speed_observer_update(&self, T_s, InputSignal(1, 0), "
            "InputSignal(2, 0));\n",
            SAMPLING,
            outputs=(1, 1),
        ),
        params,
        sig.sfunction("speed_observer"),
        feedthrough=[1, 0, 0],
        mask=mask,
    )


def current_limiter(sig: Signals) -> CBlock:
    """Current limiter (CurrentLimiter)."""
    mask = Mask(
        "CurrentLimiter (motulator)",
        "Current limiter (CurrentLimiter): the magnitude of the current reference is "
        "limited to i_max.",
        [Param("i_max", "i_max: Maximum current (A), peak value", "cfg.i_max")],
    )
    start = checks(["i_max"], ["i_max"]) + "i_max = P(0, 0);\n"
    output = (
        f"double complex i = current_limiter(i_max, {complex_in(0)});\n"
        + complex_out(0, "i")
    )
    return CBlock(
        "CurrentLimiter",
        [Port("i", 2)],
        [Port("i_lim", 2)],
        sig.function_code(output, start, "static double i_max;\n"),
        ["i_max"],
        sig.sfunction("current_limiter"),
        sample_time=None,
        mask=mask,
    )


def rate_limiter(sig: Signals) -> CBlock:
    """Rate limiter of the speed reference (RateLimiter of VHzControlSystem)."""
    mask = Mask(
        "RateLimiter (motulator)",
        "Rate limiter (RateLimiter): the rising and falling rates of the signal are "
        "limited to rate_limit, e.g., the slew rate of the speed reference "
        "(mechanical rad/s²) in VHzControlSystem.",
        [Param("rate_limit", "rate_limit: Rate limit, inf = none", "slew_rate"), T_S],
    )
    params = mask_params(mask)
    start = (
        checks(params, params) + "rate_limiter_init(&self, P(0, 0));\nT_s = P(1, 0);\n"
    )
    output = (
        "y = rate_limiter_compute_output(&self, T_s, InputSignal(1, 0));\n"
        "OutputSignal(0, 0) = y;\n"
    )
    return CBlock(
        "RateLimiter",
        [Port(ENABLE, 1), Port("u", 1)],
        [Port("y", 1)],
        sig.class_code(
            "RateLimiter",
            start,
            output,
            "rate_limiter_update(&self, y);\n",
            SAMPLING + "static double y;\n",
        ),
        params,
        sig.sfunction("rate_limiter"),
        mask=mask,
    )


def pwm_values(pwm: PWM, T_s: float) -> dict[str, Any]:
    """
    Get the parameter values of the PWM (the struct pwm of the model
    initialization).

    Only the duty-ratio error model `d_err = dead_time_error(i_abc, d_abc, t_d, T_s,
    sign)` with the sampling period `T_s` of the control system and `sign = np.sign`
    (the default) or `sign = lambda i: np.tanh(i/i_0)` is supported. Since `d_err`
    is a function, the dead time `t_d` and the current scale `i_0` are identified
    from its values at the duty ratios of 0.5, where `d_err = t_d/(2*T_s)*sign(i)`,
    and the function is checked at test points, also near zero current. The minimum
    duty ratio `d_min` of a switching leg is a parameter of the PWM.

    """
    d_min = float(pwm.d_min)
    if pwm.d_err is None:
        return {
            "pwm_t_d": 0.0,
            "pwm_i_0": 0.0,
            "pwm_feedforward": int(pwm.feedforward),
            "pwm_d_min": d_min,
            "pwm_overmodulation": pwm.overmodulation,
        }
    d_err = pwm.d_err
    d_half = np.full(3, 0.5)

    def sign(i: float) -> float:
        """Current direction scaled by the error at the duty ratios of 0.5."""
        return float(d_err(np.array([i, -i, 0.0]), d_half)[0])

    # The sign function saturates far from zero current
    t_d = float(f"{2 * T_s * sign(1e6):.12g}")  # Remove the rounding errors
    i_0 = 0.0
    if t_d > 0 and sign(1e-300) < 0.5 * t_d / (2 * T_s):
        # Smooth sign function: bisect the current at which it reaches tanh(1)
        lo, hi = 0.0, 1e6
        target = np.tanh(1) * t_d / (2 * T_s)
        for _ in range(200):
            mid = 0.5 * (lo + hi)
            lo, hi = (mid, hi) if sign(mid) < target else (lo, mid)
        i_0 = float(f"{0.5 * (lo + hi):.12g}")
    rng = np.random.default_rng(0)
    i_test = rng.uniform(-10, 10, (40, 3))
    i_test[:, 0] = 0  # The signum function is zero at zero current
    # Currents near zero, where the sign functions differ
    i_near = np.array([1e-9, 1e-6, 1e-3, 1e-2, 0.1, 0.3, 1.0])
    if i_0 > 0:
        i_near = np.concatenate((i_near, i_0 * np.array([0.1, 0.5, 1.0, 2.0, 5.0])))
    for k, i in enumerate(i_near):
        i_test[5 + 2 * k, 1:] = [i, -i]
        i_test[6 + 2 * k, 1:] = [-i, 0.5 * i]
    d_test = rng.uniform(0, 1, (40, 3))
    d_test[:5] = [[0, 1, 0.5], [1e-3, 1 - 1e-3, 0.5], [0, 0, 1], [1, 1, 0], [0.5] * 3]
    d_test[5:30, 1:] = 0.5  # Duty ratios at which the error is not suppressed
    for i_abc, d_abc in zip(i_test, d_test, strict=True):
        if t_d <= 0 or not np.allclose(
            d_err(i_abc, d_abc),
            dead_time_error(i_abc, d_abc, t_d, T_s, _tanh_sign(i_0)),
            rtol=0,
            atol=1e-12,
        ):
            raise NotImplementedError(
                "Only d_err = dead_time_error(i_abc, d_abc, t_d, T_s, sign) with "
                "sign=np.sign or sign=lambda i: np.tanh(i/i_0) and the sampling "
                "period T_s of the control system supported"
            )
    return {
        "pwm_t_d": t_d,
        "pwm_i_0": i_0,
        "pwm_feedforward": int(pwm.feedforward),
        "pwm_d_min": d_min,
        "pwm_overmodulation": pwm.overmodulation,
    }


def _tanh_sign(i_0: float) -> Callable[[np.ndarray], np.ndarray]:
    """Current-direction function `tanh(i/i_0)`, or `np.sign` if `i_0` is zero."""
    if i_0 == 0:
        return np.sign
    return lambda i: np.tanh(i / i_0)


# %%
# Blocks of the methods of the control systems and of the monitored signals
def get_measurement(
    sig: Signals, inputs: list[Port], fields: list[tuple[str, str]], prelude: str = ""
) -> CBlock:
    """Measurements (get_measurement): the fields of meas from the inputs."""
    output = (
        prelude + f"{sig.vectors['meas'][0]} meas;\n"
        "/* Measurements, the DC-bus voltage limited to U_DC_MIN */\n"
        + "".join(f"meas.{n} = {v};\n" for n, v in fields)
        + sig.write(0, "meas", "meas")
    )
    return CBlock(
        "get_measurement",
        inputs,
        [sig.port("meas")],
        sig.function_code(output, workspace=C_U_DC_MIN),
        ["T_s"],
        sig.sfunction("get_measurement"),
    )


def abc_input(name: str, port: int) -> str:
    """C code reading a three-phase input."""
    return (
        f"double {name}[3] = {{InputSignal({port}, 0), InputSignal({port}, 1),\n"
        f"    InputSignal({port}, 2)}};\n"
    )


def modulate(sig: Signals, u: str) -> CBlock:
    """
    Voltage reference for the PWM (modulate): the voltage reference `u` (e.g.,
    ref.u_s) in stationary coordinates, and the angular speed of the coordinates.
    """
    output = (
        sig.read(0, "fbk")
        + "/* Voltage reference in stationary coordinates */\n"
        + f"double complex u_c_ref_ab = cexp(I * fbk.theta_c) * {complex_in(1)};\n"
        + complex_out(0, "u_c_ref_ab")
        + "OutputSignal(1, 0) = fbk.w_c;\n"
    )
    return CBlock(
        "modulate",
        [sig.port("fbk"), Port(u, 2)],
        [Port("u_c_ref_ab", 2), Port("w", 1)],
        sig.function_code(output),
        ["T_s"],
        sig.sfunction("modulate"),
    )


def monitor(
    sig: Signals,
    outputs: dict[str, list[str]],
    monitored: dict[str, str],
    inputs: list[Port],
    prelude: str = "",
) -> CBlock:
    """
    Monitored signals: the groups `outputs` of the expressions `monitored` of the
    feedback signals fbk, the references ref, and the other `inputs`.
    """
    code = sig.function_code(
        sig.read(1, "fbk")
        + sig.read(2, "ref")
        + monitored_code(outputs, monitored, prelude=prelude, first=0)
    )
    return CBlock(
        MONITOR,
        [Port(ENABLE, 1), sig.port("fbk"), sig.port("ref"), *inputs],
        [Port(name, len(signals)) for name, signals in outputs.items()],
        block_enable_code(code, [], [len(v) for v in outputs.values()], 0.0),
        ["T_s"],
        sig.sfunction("monitored_signals"),
    )


# %%
# Top levels
def vector_control_system(
    sig: Signals,
    name: str,
    inputs: list[Port],
    measurement: CBlock,
    vector_ctrl: Subsystem,
    signals: CBlock,
) -> Subsystem:
    """
    Vector control system of a drive (VectorControlSystem): the contents of the
    masked subsystem of the control system, whose mask has the sampling period T_s.

    The vector controller has the inputs `enable`, `tau_M_ref`, `meas`, `u_c_ab`,
    and optionally `u_c_zoh_ab`, and the outputs `fbk` and `ref`. The inputs of the
    monitored signals are `enable`, `fbk`, `ref`, and `w_M_ref`.

    """
    vc = vector_ctrl.name
    zoh = "u_c_zoh_ab" in [p.name for p in vector_ctrl.inputs]
    fbk, ref = sig.width("fbk"), sig.width("ref")
    # The feedback signals and the references to the speed controller and to the
    # monitored signals by tags, the others by wires
    tags = [
        Tag("Goto fbk", "fbk", fbk, goto=True),
        Tag("Goto ref", "ref", ref, goto=True),
        Tag("From fbk", "fbk", fbk, goto=False),
        Tag("From ref", "ref", ref, goto=False),
        Tag("From fbk 2", "fbk", fbk, goto=False),
        Tag("From ref 2", "ref", ref, goto=False),
    ]
    meas = [(p.name, f"get_measurement:{p.name}") for p in measurement.inputs]
    return Subsystem(
        name,
        inputs,
        [Port("d_abc", 3)],
        [
            measurement,
            *tags,
            sig.selector("fbk", "w_M"),
            sig.selector("ref", "tau_M"),
            speed_controller(sig),
            pwm(sig),
            vector_ctrl,
            sig.selector("ref", "u_s", complex_=True),
            modulate(sig, "u_s"),
            signals,
        ],
        [
            (ENABLE, "SpeedController:enable"),
            (ENABLE, "PWM:enable"),
            (ENABLE, f"{vc}:enable"),
            (ENABLE, f"{MONITOR}:enable"),
            ("w_M_ref", "SpeedController:w_M_ref"),
            ("w_M_ref", f"{MONITOR}:w_M_ref"),
            *meas,
            ("get_measurement:meas", "PWM:meas"),
            ("get_measurement:meas", f"{vc}:meas"),
            ("From fbk", "fbk.w_M:u"),
            ("From ref", "ref.tau_M:u"),
            ("fbk.w_M:y", "SpeedController:w_M"),
            ("ref.tau_M:y", "SpeedController:tau_M"),
            ("SpeedController:tau_M_ref", f"{vc}:tau_M_ref"),
            ("PWM:u_c_ab", f"{vc}:u_c_ab"),
            *([("PWM:u_c_zoh_ab", f"{vc}:u_c_zoh_ab")] if zoh else []),
            ("PWM:d_abc", "d_abc"),
            (f"{vc}:fbk", "Goto fbk"),
            (f"{vc}:fbk", "modulate:fbk"),
            (f"{vc}:ref", "Goto ref"),
            (f"{vc}:ref", "ref.u_s:u"),
            ("ref.u_s:y", "modulate:u_s"),
            ("modulate:u_c_ref_ab", "PWM:u_c_ref_ab"),
            ("modulate:w", "PWM:w"),
            ("From fbk 2", f"{MONITOR}:fbk"),
            ("From ref 2", f"{MONITOR}:ref"),
        ],
        columns=[
            [p.name for p in inputs],
            ["From fbk", "From ref", "get_measurement"],
            ["fbk.w_M", "ref.tau_M"],
            ["SpeedController", "PWM"],
            [vc, "d_abc"],
            ["Goto fbk", "ref.u_s", "Goto ref", "From fbk 2", "From ref 2"],
            ["modulate", MONITOR],
        ],
        align={
            "fbk.w_M:u": "From fbk",
            "ref.tau_M:u": "From ref",
            "SpeedController:w_M": "fbk.w_M:y",
            "get_measurement:meas": "SpeedController:tau_M_ref+1",
            "PWM:meas": "get_measurement:meas+2",
            f"{vc}:meas": "get_measurement:meas",
            "d_abc": "PWM:d_abc",
            "modulate:fbk": f"{vc}:fbk",
            "ref.u_s:y": "modulate:u_s+1",
            "Goto fbk": f"{vc}:fbk-1",
            "Goto ref": "ref.u_s:u+1",
            f"{MONITOR}:fbk": "From fbk 2",
        },
        lanes={"PWM:u_c_ref_ab": "below:1", "PWM:w": "below:0"},
        tags=[ENABLE, "w_M_ref"],
    )


def grid_converter_control_system(
    sig: Signals,
    name: str,
    inputs: list[Port],
    measurement: CBlock,
    inner_ctrl: Subsystem,
    signals: CBlock,
) -> Subsystem:
    """
    Control system of a grid converter (GridConverterControlSystem): the contents of
    the masked subsystem of the control system, whose mask has the sampling period
    T_s.

    The inputs are `enable`, the two references, and the inputs of the measurements.
    The inner controller has the inputs `enable`, the references, `meas`, and
    `u_c_ab`, and the outputs `fbk` and `ref`. The inputs of the monitored signals
    are `enable`, `fbk`, and `ref`.

    """
    ic = inner_ctrl.name
    refs = [p.name for p in inputs[1:3]]
    fbk, ref = sig.width("fbk"), sig.width("ref")
    # The feedback signals and the references to the monitored signals by tags
    tags = [
        Tag("Goto fbk", "fbk", fbk, goto=True),
        Tag("Goto ref", "ref", ref, goto=True),
        Tag("From fbk", "fbk", fbk, goto=False),
        Tag("From ref", "ref", ref, goto=False),
    ]
    return Subsystem(
        name,
        inputs,
        [Port("d_abc", 3)],
        [
            measurement,
            pwm(sig),
            inner_ctrl,
            *tags,
            sig.selector("ref", "u_c", complex_=True),
            modulate(sig, "u_c"),
            signals,
        ],
        [
            (ENABLE, "PWM:enable"),
            (ENABLE, f"{ic}:enable"),
            (ENABLE, f"{MONITOR}:enable"),
            *((r, f"{ic}:{r}") for r in refs),
            *((p.name, f"get_measurement:{p.name}") for p in measurement.inputs),
            ("get_measurement:meas", "PWM:meas"),
            ("get_measurement:meas", f"{ic}:meas"),
            ("PWM:u_c_ab", f"{ic}:u_c_ab"),
            ("PWM:d_abc", "d_abc"),
            (f"{ic}:fbk", "Goto fbk"),
            (f"{ic}:fbk", "modulate:fbk"),
            (f"{ic}:ref", "Goto ref"),
            (f"{ic}:ref", "ref.u_c:u"),
            ("ref.u_c:y", "modulate:u_c"),
            ("modulate:u_c_ref_ab", "PWM:u_c_ref_ab"),
            ("modulate:w", "PWM:w"),
            ("From fbk", f"{MONITOR}:fbk"),
            ("From ref", f"{MONITOR}:ref"),
        ],
        columns=[
            [p.name for p in inputs],
            ["get_measurement"],
            ["PWM"],
            [ic, "d_abc"],
            ["Goto fbk", "ref.u_c", "Goto ref", "From fbk", "From ref"],
            ["modulate", MONITOR],
        ],
        align={
            refs[0]: f"{ic}:{refs[0]}-1",
            refs[1]: f"{ic}:{refs[1]}",
            "get_measurement:meas": f"{ic}:meas+1",
            "PWM:meas": "get_measurement:meas+2",
            "d_abc": "PWM:d_abc",
            "modulate:fbk": f"{ic}:fbk",
            "ref.u_c:y": "modulate:u_c+1",
            "Goto fbk": f"{ic}:fbk-1",
            "Goto ref": "ref.u_c:u+1",
            f"{MONITOR}:fbk": "From fbk",
        },
        lanes={"PWM:u_c_ref_ab": "below:1", "PWM:w": "below:0"},
        tags=[ENABLE],
    )


def vhz_control_system(
    sig: Signals,
    name: str,
    inputs: list[Port],
    measurement: CBlock,
    vhz_ctrl: Subsystem,
    signals: CBlock,
) -> Subsystem:
    """
    V/Hz control system of a drive (VHzControlSystem): the contents of the masked
    subsystem of the control system, whose mask has the sampling period T_s.

    The inputs are `enable`, the speed reference `w_M_ref`, and the inputs of the
    measurements. The speed reference is limited by the rate limiter. The V/Hz
    controller has the inputs `enable`, the rate-limited speed reference `w_M`,
    `meas`, and `u_c_ab`, and the outputs `fbk` and `ref`. The inputs of the
    monitored signals are `enable`, `fbk`, `ref`, and `w_M_ref` (the rate-limited
    speed reference).

    """
    vc = vhz_ctrl.name
    fbk, ref = sig.width("fbk"), sig.width("ref")
    # The feedback signals, the references, and the rate-limited speed reference to
    # the monitored signals by tags
    tags = [
        Tag("Goto w_M", "w_M", 1, goto=True),
        Tag("Goto fbk", "fbk", fbk, goto=True),
        Tag("Goto ref", "ref", ref, goto=True),
        Tag("From fbk", "fbk", fbk, goto=False),
        Tag("From ref", "ref", ref, goto=False),
        Tag("From w_M", "w_M", 1, goto=False),
    ]
    return Subsystem(
        name,
        inputs,
        [Port("d_abc", 3)],
        [
            measurement,
            rate_limiter(sig),
            pwm(sig),
            vhz_ctrl,
            *tags,
            sig.selector("ref", "u_s", complex_=True),
            modulate(sig, "u_s"),
            signals,
        ],
        [
            (ENABLE, "RateLimiter:enable"),
            (ENABLE, "PWM:enable"),
            (ENABLE, f"{vc}:enable"),
            (ENABLE, f"{MONITOR}:enable"),
            ("w_M_ref", "RateLimiter:u"),
            ("RateLimiter:y", f"{vc}:w_M"),
            ("RateLimiter:y", "Goto w_M"),
            *((p.name, f"get_measurement:{p.name}") for p in measurement.inputs),
            ("get_measurement:meas", "PWM:meas"),
            ("get_measurement:meas", f"{vc}:meas"),
            ("PWM:u_c_ab", f"{vc}:u_c_ab"),
            ("PWM:d_abc", "d_abc"),
            (f"{vc}:fbk", "Goto fbk"),
            (f"{vc}:fbk", "modulate:fbk"),
            (f"{vc}:ref", "Goto ref"),
            (f"{vc}:ref", "ref.u_s:u"),
            ("ref.u_s:y", "modulate:u_s"),
            ("modulate:u_c_ref_ab", "PWM:u_c_ref_ab"),
            ("modulate:w", "PWM:w"),
            ("From fbk", f"{MONITOR}:fbk"),
            ("From ref", f"{MONITOR}:ref"),
            ("From w_M", f"{MONITOR}:w_M_ref"),
        ],
        columns=[
            [p.name for p in inputs],
            ["RateLimiter", "get_measurement"],
            ["Goto w_M", "PWM"],
            [vc, "d_abc"],
            ["Goto fbk", "ref.u_s", "Goto ref", "From fbk", "From ref", "From w_M"],
            ["modulate", MONITOR],
        ],
        align={
            "RateLimiter:y": f"{vc}:w_M",
            "w_M_ref": "RateLimiter:u",
            "Goto w_M": "RateLimiter:y-1",
            "get_measurement:meas": f"{vc}:meas+1",
            "PWM:meas": "get_measurement:meas+2",
            "d_abc": "PWM:d_abc",
            "modulate:fbk": f"{vc}:fbk",
            "ref.u_s:y": "modulate:u_s+1",
            "Goto fbk": f"{vc}:fbk-1",
            "Goto ref": "ref.u_s:u+1",
            f"{MONITOR}:fbk": "From fbk",
        },
        lanes={"PWM:u_c_ref_ab": "below:1", "PWM:w": "below:0"},
        tags=[ENABLE],
    )


def control_block(
    name: str,
    description: str,
    inputs: list[Port],
    outputs: dict[str, list[str]],
    netlist: Callable[[], Subsystem],
    cls: str = "VectorControlSystem",
) -> ControlBlock:
    """Control-system block of a control system of the class `cls` (e.g.,
    VectorControlSystem), whose contents are `netlist`."""
    return ControlBlock(
        name=name,
        mask_type=f"{cls} (motulator)",
        description=description
        + " Each class of motulator is a block with a mask of its arguments. The "
        "top-level blocks refer to the variables of the model initialization, and the "
        "blocks inside them get their parameters as in the constructors of motulator. "
        "T_s is the sampling period of the measurements." + ENABLE_DESCRIPTION,
        mask_params=[MaskParam("T_s", "T_s: Sampling period (s)", cls, "", True)],
        inputs=[p.name for p in inputs],
        input_widths=[p.width for p in inputs],
        outputs=outputs,
        netlist=netlist,
    )


# Mask values of the control systems: the sampling period of the configuration
VALUES = {"T_s": "cfg.T_s"}


# %%
# Model initialization
def _value(value: Any) -> str:
    """Value in the model initialization: an integer without the decimal point."""
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, (int, float)) and float(value).is_integer() and value < 1e15:
        return str(int(value))
    return _fmt_mask(value) if isinstance(value, float) else _fmt(value)


def assign(name: str, value: Any) -> str:
    """Assignment of the model initialization."""
    return f"{name} = {_value(value)};\n"


def init_header(variables: list[tuple[str, Any]], comment: str) -> str:
    """The comment and the variables of the system model."""
    return (
        comment + "\n"
        "%% System model\n" + "".join(assign(n, v) for n, v in variables) + "\n"
        "%% Control system ([] = None, the default)\n"
    )


def speed_ctrl_init(values: dict[str, Any]) -> str:
    """The struct speed_ctrl of the model initialization."""
    return "% Speed controller (SpeedController)\n" + "".join(
        assign(f"speed_ctrl.{n}", values[f"speed_{n}"])
        for n in ("J", "alpha_s", "alpha_i", "tau_M_max")
    )


def pwm_init(values: dict[str, Any]) -> str:
    """The struct pwm of the model initialization."""
    return (
        "% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,\n"
        "% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its\n"
        "% compensation, the minimum duty ratio of a switching leg, and the\n"
        "% overmodulation ('MPE' or 'MME')\n"
        + "".join(
            assign(f"pwm.{n}", values[f"pwm_{n}"])
            for n in ("t_d", "i_0", "feedforward", "d_min", "overmodulation")
        )
    )


# Comment of the model initialization of a PLECS model
INIT_COMMENT = (
    "% Generated from motulator. The blocks of the control system have masks of the\n"
    "% arguments of their classes, which refer to the structs below, as in the\n"
    "% motulator API.\n"
)
