% Build the Simulink model gfl_10kva_lcl.slx in the folder of this script.
% Generated by motulator_export.simulink from motulator. The parameters
% are defined by the script init_gfl_10kva_lcl.m.
%
% The S-functions of the blocks of the control system are compiled with
% mex, which needs a C99 compiler with complex.h (gcc, clang, or
% MinGW-w64, not MSVC), see mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_export', 'simulink'));

s = struct();
s.folder = here;
s.name = 'gfl_10kva_lcl';
s.init_script = 'init_gfl_10kva_lcl';
s.ac_filter = 'lcl';
s.refs = { ...
    'enable', 'constant', 1.0
    'p_g_ref', 'step', [0.020050000000000002 0.0 5000.0]
    'q_g_ref', 'step', [0.03995 0.0 4000.0]
    };
s.scope = { ...
    'Power', [7.0 8.0 9.0 10.0]
    'Converter current', [1.0 2.0 3.0]
    'Current', [11.0 12.0 13.0 14.0]
    'PLL', [15.0 16.0 17.0]
    };
s.control.name = 'Grid-following control';
s.control.sfunction = {'sfun_gfl_get_measurement', 'sfun_gfl_pwm', 'sfun_gfl_pwm_realized_voltage', 'sfun_gfl_pll', 'sfun_gfl_current_reference', 'sfun_gfl_current_limiter', 'sfun_gfl_current_controller', 'sfun_gfl_modulate', 'sfun_gfl_monitored_signals'};
s.control.mask_type = 'GridConverterControlSystem (motulator)';
s.control.description = 'Current-vector grid-following control with a PLL in the power-control mode (GridConverterControlSystem with CurrentVectorController). Each class of motulator is a block with a mask of its arguments. The top-level blocks refer to the variables of the model initialization, and the blocks inside them get their parameters as in the constructors of motulator. T_s is the sampling period of the measurements. While the input enable is not positive, the duty ratios are 0.5 and the state is reset to its initial value.';
s.control.mask = { ...
    'T_s', 'T_s: Sampling period (s)', 'GridConverterControlSystem', 'cfg.T_s'
    };
s.control.mask_init = '';
s.control.inputs = {'enable', 'p_g_ref', 'q_g_ref', 'i_c_abc', 'u_g_line', 'u_dc'};
s.control.netlist.blocks = { ...
    'enable', 'Inport', [40.0 43.0 70.0 57.0], {'Port', '1'}
    'p_g_ref', 'Inport', [40.0 78.0 70.0 92.0], {'Port', '2'}
    'q_g_ref', 'Inport', [40.0 133.0 70.0 147.0], {'Port', '3'}
    'i_c_abc', 'Inport', [40.0 188.0 70.0 202.0], {'Port', '4'}
    'u_g_line', 'Inport', [40.0 243.0 70.0 257.0], {'Port', '5'}
    'u_dc', 'Inport', [40.0 298.0 70.0 312.0], {'Port', '6'}
    'd_abc', 'Outport', [890.0 381.0 920.0 395.0], {'Port', '1'}
    'signals', 'Outport', [1605.0 258.0 1635.0 272.0], {'Port', '2'}
    'get_measurement', 'S-Function', [250.0 180.0 390.0 270.0], {'FunctionName', 'sfun_gfl_get_measurement', 'Parameters', '1'}
    'PWM', 'Subsystem', [570.0 255.0 710.0 415.0], {'ContentPreviewEnabled', 'off'}
    'CurrentVectorController', 'Subsystem', [890.0 40.0 1030.0 240.0], {'ContentPreviewEnabled', 'off'}
    'Goto fbk', 'Goto', [1105.0 38.0 1175.0 52.0], {'GotoTag', 'fbk', 'ShowName', 'off', 'TagVisibility', 'local'}
    'Goto ref', 'Goto', [1105.0 203.0 1175.0 217.0], {'GotoTag', 'ref', 'ShowName', 'off', 'TagVisibility', 'local'}
    'From fbk', 'From', [1105.0 258.0 1175.0 272.0], {'GotoTag', 'fbk', 'ShowName', 'off'}
    'From ref', 'From', [1105.0 313.0 1175.0 327.0], {'GotoTag', 'ref', 'ShowName', 'off'}
    'ref.u_c', 'Selector', [1105.0 150.0 1155.0 180.0], {'NumberOfDimensions', '1', 'IndexOptions', 'Index vector (dialog)', 'Indices', '[5 6]', 'InputPortWidth', '6'}
    'modulate', 'S-Function', [1340.0 75.0 1480.0 135.0], {'FunctionName', 'sfun_gfl_modulate', 'Parameters', '1'}
    'Monitored signals', 'S-Function', [1340.0 220.0 1480.0 310.0], {'FunctionName', 'sfun_gfl_monitored_signals', 'Parameters', '1'}
    'Mux signals', 'Mux', [1558.0 220.0 1563.0 310.0], {'Inputs', '[4 4 3]', 'ShowName', 'off'}
    'From PWM.enable', 'From', [475.0 268.0 545.0 282.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'From CurrentVectorController.enable', 'From', [795.0 53.0 865.0 67.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'From Monitored signals.enable', 'From', [1245.0 228.0 1315.0 242.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'Goto enable', 'Goto', [110.0 43.0 180.0 57.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    'PWM/enable', 'Inport', [40.0 243.0 70.0 257.0], {'Port', '1'}
    'PWM/meas', 'Inport', [40.0 78.0 70.0 92.0], {'Port', '2'}
    'PWM/u_c_ref_ab', 'Inport', [40.0 133.0 70.0 147.0], {'Port', '3'}
    'PWM/w', 'Inport', [40.0 188.0 70.0 202.0], {'Port', '4'}
    'PWM/u_c_ab', 'Outport', [845.0 55.0 875.0 69.0], {'Port', '1'}
    'PWM/u_c_zoh_ab', 'Outport', [845.0 113.0 875.0 127.0], {'Port', '2'}
    'PWM/d_abc', 'Outport', [845.0 153.0 875.0 167.0], {'Port', '3'}
    'PWM/compute_output', 'S-Function', [355.0 100.0 495.0 220.0], {'FunctionName', 'sfun_gfl_pwm', 'Parameters', '1, 1, 1, 1, 1, 1'}
    'PWM/get_realized_voltage', 'S-Function', [645.0 40.0 785.0 130.0], {'FunctionName', 'sfun_gfl_pwm_realized_voltage', 'Parameters', '1, 1, 1, 1, 1, 1'}
    'PWM/From compute_output.enable', 'From', [260.0 108.0 330.0 122.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'PWM/From get_realized_voltage.enable', 'From', [550.0 48.0 620.0 62.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'PWM/Goto enable', 'Goto', [110.0 243.0 180.0 257.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    'CurrentVectorController/enable', 'Inport', [40.0 443.0 70.0 457.0], {'Port', '1'}
    'CurrentVectorController/p_g_ref', 'Inport', [40.0 93.0 70.0 107.0], {'Port', '2'}
    'CurrentVectorController/q_g_ref', 'Inport', [40.0 168.0 70.0 182.0], {'Port', '3'}
    'CurrentVectorController/meas', 'Inport', [40.0 333.0 70.0 347.0], {'Port', '4'}
    'CurrentVectorController/u_c_ab', 'Inport', [40.0 388.0 70.0 402.0], {'Port', '5'}
    'CurrentVectorController/fbk', 'Outport', [1450.0 333.0 1480.0 347.0], {'Port', '1'}
    'CurrentVectorController/ref', 'Outport', [1450.0 198.0 1480.0 212.0], {'Port', '2'}
    'CurrentVectorController/PLL', 'S-Function', [325.0 295.0 465.0 385.0], {'FunctionName', 'sfun_gfl_pll', 'Parameters', '1, 1, 1, 1'}
    'CurrentVectorController/fbk.u_g', 'Selector', [525.0 235.0 575.0 265.0], {'NumberOfDimensions', '1', 'IndexOptions', 'Index vector (dialog)', 'Indices', '[5]', 'InputPortWidth', '13'}
    'CurrentVectorController/compute_output', 'S-Function', [650.0 175.0 790.0 265.0], {'FunctionName', 'sfun_gfl_current_reference', 'Parameters', '1'}
    'CurrentVectorController/CurrentLimiter', 'S-Function', [865.0 220.0 1005.0 280.0], {'FunctionName', 'sfun_gfl_current_limiter', 'Parameters', '1'}
    'CurrentVectorController/CurrentController', 'S-Function', [1170.0 205.0 1310.0 295.0], {'FunctionName', 'sfun_gfl_current_controller', 'Parameters', '1, 1, 1, 1'}
    'CurrentVectorController/Mux ref', 'Mux', [1398.0 145.0 1403.0 265.0], {'Inputs', '[1 1 2 2]', 'ShowName', 'off'}
    'CurrentVectorController/From PLL.enable', 'From', [230.0 303.0 300.0 317.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'CurrentVectorController/From CurrentController.enable', 'From', [1075.0 213.0 1145.0 227.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'CurrentVectorController/Goto enable', 'Goto', [110.0 443.0 180.0 457.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    };
s.control.netlist.aligns = { ...
    '', 'Goto fbk', 'Inport', 1.0, 'CurrentVectorController', 'Outport', 1.0, -45.0
    '', 'modulate', 'Inport', 1.0, 'CurrentVectorController', 'Outport', 1.0, 0.0
    '', 'q_g_ref', 'Outport', 1.0, 'CurrentVectorController', 'Inport', 3.0, 0.0
    '', 'get_measurement', 'Outport', 1.0, 'CurrentVectorController', 'Inport', 4.0, 45.0
    '', 'PWM', 'Inport', 2.0, 'get_measurement', 'Outport', 1.0, 90.0
    '', 'd_abc', 'Inport', 1.0, 'PWM', 'Outport', 3.0, 0.0
    '', 'ref.u_c', 'Outport', 1.0, 'modulate', 'Inport', 2.0, 45.0
    '', 'Goto ref', 'Inport', 1.0, 'ref.u_c', 'Inport', 1.0, 45.0
    '', 'Monitored signals', 'Inport', 2.0, 'From fbk', 'Outport', 1.0, 0.0
    '', 'Mux signals', 'Inport', 1.0, 'Monitored signals', 'Outport', 1.0, 0.0
    '', 'signals', 'Inport', 1.0, 'Mux signals', 'Outport', 1.0, 0.0
    '', 'From PWM.enable', 'Outport', 1.0, 'PWM', 'Inport', 1.0, 0.0
    '', 'From CurrentVectorController.enable', 'Outport', 1.0, 'CurrentVectorController', 'Inport', 1.0, 0.0
    '', 'From Monitored signals.enable', 'Outport', 1.0, 'Monitored signals', 'Inport', 1.0, 0.0
    '', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    'PWM', 'get_realized_voltage', 'Inport', 3.0, 'compute_output', 'Outport', 1.0, -45.0
    'PWM', 'u_c_ab', 'Inport', 1.0, 'get_realized_voltage', 'Outport', 1.0, 0.0
    'PWM', 'd_abc', 'Inport', 1.0, 'compute_output', 'Outport', 1.0, 0.0
    'PWM', 'meas', 'Outport', 1.0, 'get_realized_voltage', 'Inport', 2.0, 0.0
    'PWM', 'From compute_output.enable', 'Outport', 1.0, 'compute_output', 'Inport', 1.0, 0.0
    'PWM', 'From get_realized_voltage.enable', 'Outport', 1.0, 'get_realized_voltage', 'Inport', 1.0, 0.0
    'PWM', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    'CurrentVectorController', 'CurrentLimiter', 'Inport', 1.0, 'compute_output', 'Outport', 3.0, 0.0
    'CurrentVectorController', 'CurrentController', 'Inport', 2.0, 'CurrentLimiter', 'Outport', 1.0, 0.0
    'CurrentVectorController', 'Mux ref', 'Inport', 4.0, 'CurrentController', 'Outport', 1.0, 0.0
    'CurrentVectorController', 'ref', 'Inport', 1.0, 'Mux ref', 'Outport', 1.0, 0.0
    'CurrentVectorController', 'p_g_ref', 'Outport', 1.0, 'compute_output', 'Inport', 1.0, -90.0
    'CurrentVectorController', 'q_g_ref', 'Outport', 1.0, 'compute_output', 'Inport', 2.0, -45.0
    'CurrentVectorController', 'fbk.u_g', 'Outport', 1.0, 'compute_output', 'Inport', 3.0, 0.0
    'CurrentVectorController', 'PLL', 'Outport', 1.0, 'fbk.u_g', 'Inport', 1.0, 90.0
    'CurrentVectorController', 'fbk', 'Inport', 1.0, 'PLL', 'Outport', 1.0, 0.0
    'CurrentVectorController', 'meas', 'Outport', 1.0, 'PLL', 'Inport', 2.0, 0.0
    'CurrentVectorController', 'From PLL.enable', 'Outport', 1.0, 'PLL', 'Inport', 1.0, 0.0
    'CurrentVectorController', 'From CurrentController.enable', 'Outport', 1.0, 'CurrentController', 'Inport', 1.0, 0.0
    'CurrentVectorController', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    };
s.control.netlist.lines = { ...
    '', 'From PWM.enable/1', 'PWM/1', []
    '', 'From CurrentVectorController.enable/1', 'CurrentVectorController/1', []
    '', 'From Monitored signals.enable/1', 'Monitored signals/1', []
    '', 'p_g_ref/1', 'CurrentVectorController/2', {'x', 735.0}
    '', 'q_g_ref/1', 'CurrentVectorController/3', []
    '', 'i_c_abc/1', 'get_measurement/1', []
    '', 'u_g_line/1', 'get_measurement/2', {'x', 200.0}
    '', 'u_dc/1', 'get_measurement/3', {'x', 215.0}
    '', 'get_measurement/1', 'PWM/2', {'x', 415.0}
    '', 'get_measurement/1', 'CurrentVectorController/4', {'x', 750.0}
    '', 'PWM/1', 'CurrentVectorController/5', {'x', 765.0}
    '', 'PWM/3', 'd_abc/1', []
    '', 'CurrentVectorController/1', 'Goto fbk/1', {'x', 1055.0}
    '', 'CurrentVectorController/1', 'modulate/1', []
    '', 'CurrentVectorController/2', 'Goto ref/1', {'x', 1070.0}
    '', 'CurrentVectorController/2', 'ref.u_c/1', {'x', 1070.0}
    '', 'ref.u_c/1', 'modulate/2', {'x', 1215.0}
    '', 'modulate/1', 'PWM/3', {'x', 1520.0, 'y', 470.0, 'x', 430.0}
    '', 'modulate/2', 'PWM/4', {'x', 1505.0, 'y', 455.0, 'x', 445.0}
    '', 'From fbk/1', 'Monitored signals/2', []
    '', 'From ref/1', 'Monitored signals/3', {'x', 1200.0}
    '', 'Monitored signals/1', 'Mux signals/1', []
    '', 'Monitored signals/2', 'Mux signals/2', []
    '', 'Monitored signals/3', 'Mux signals/3', []
    '', 'Mux signals/1', 'signals/1', []
    '', 'enable/1', 'Goto enable/1', []
    'PWM', 'From compute_output.enable/1', 'compute_output/1', []
    'PWM', 'From get_realized_voltage.enable/1', 'get_realized_voltage/1', []
    'PWM', 'meas/1', 'compute_output/2', {'x', 230.0}
    'PWM', 'meas/1', 'get_realized_voltage/2', []
    'PWM', 'u_c_ref_ab/1', 'compute_output/3', {'x', 215.0}
    'PWM', 'w/1', 'compute_output/4', {'x', 200.0}
    'PWM', 'compute_output/1', 'd_abc/1', []
    'PWM', 'compute_output/1', 'get_realized_voltage/3', {'x', 520.0}
    'PWM', 'get_realized_voltage/1', 'u_c_ab/1', []
    'PWM', 'get_realized_voltage/2', 'u_c_zoh_ab/1', {'x', 810.0}
    'PWM', 'enable/1', 'Goto enable/1', []
    'CurrentVectorController', 'From PLL.enable/1', 'PLL/1', []
    'CurrentVectorController', 'From CurrentController.enable/1', 'CurrentController/1', []
    'CurrentVectorController', 'meas/1', 'PLL/2', []
    'CurrentVectorController', 'u_c_ab/1', 'PLL/3', {'x', 200.0}
    'CurrentVectorController', 'PLL/1', 'fbk.u_g/1', {'x', 490.0}
    'CurrentVectorController', 'PLL/1', 'CurrentController/3', {'x', 1030.0}
    'CurrentVectorController', 'PLL/1', 'fbk/1', []
    'CurrentVectorController', 'p_g_ref/1', 'compute_output/1', {'x', 615.0}
    'CurrentVectorController', 'q_g_ref/1', 'compute_output/2', {'x', 600.0}
    'CurrentVectorController', 'fbk.u_g/1', 'compute_output/3', []
    'CurrentVectorController', 'compute_output/3', 'CurrentLimiter/1', []
    'CurrentVectorController', 'CurrentLimiter/1', 'CurrentController/2', []
    'CurrentVectorController', 'CurrentLimiter/1', 'Mux ref/3', {'x', 1045.0, 'y', 165.0, 'x', 1335.0}
    'CurrentVectorController', 'compute_output/1', 'Mux ref/1', {'x', 815.0, 'y', 40.0, 'x', 1365.0}
    'CurrentVectorController', 'compute_output/2', 'Mux ref/2', {'x', 830.0, 'y', 55.0, 'x', 1350.0}
    'CurrentVectorController', 'CurrentController/1', 'Mux ref/4', []
    'CurrentVectorController', 'Mux ref/1', 'ref/1', []
    'CurrentVectorController', 'enable/1', 'Goto enable/1', []
    };
s.control.netlist.masks = { ...
    'PWM', 'PWM (motulator)', 'Space-vector PWM with the minimum-phase-error (MPE) or the minimum-magnitude-error (MME) overmodulation (PWM), with the duty-ratio error model d_err = dead_time_error(i_abc, d_abc, t_d, T_s, sign) and its compensation, and the minimum pulses. The blocks inside are its methods compute_output and get_realized_voltage.', strjoin({ ...
    '% MME overmodulation, or MPE', ...
    'mme = strcmp(overmodulation, ''MME'');'}, newline), { ...
    'T_s', 'T_s: Sampling period (s)', 'T_s'
    't_d', 't_d: Dead time (s) in d_err = dead_time_error(i_abc, d_abc, t_d, T_s), 0 = None', 'pwm.t_d'
    'i_0', 'i_0: Current scale (A) of sign = tanh(i/i_0) in dead_time_error, 0 = np.sign', 'pwm.i_0'
    'feedforward', 'feedforward: Compensate for d_err (1) or not (0)', 'pwm.feedforward'
    'd_min', 'd_min: Minimum duty ratio of a switching leg, 0 = no limit', 'pwm.d_min'
    'overmodulation', 'overmodulation: Overmodulation, ''MPE'' or ''MME''', 'pwm.overmodulation'
    }, strjoin({ ...
    'disp(''PWM'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''meas'');', ...
    'port_label(''input'', 3, ''u_c_ref_ab'');', ...
    'port_label(''input'', 4, ''w'');', ...
    'port_label(''output'', 1, ''u_c_ab'');', ...
    'port_label(''output'', 2, ''u_c_zoh_ab'');', ...
    'port_label(''output'', 3, ''d_abc'');'}, newline)
    'CurrentVectorController', 'CurrentVectorController (motulator)', 'Grid-following current-vector controller (CurrentVectorController) in the power-control mode. The configuration cfg is a struct with the fields of CurrentVectorControllerCfg ([] = None, i.e., the default), passed to the blocks inside it, as CurrentVectorController.', '', { ...
    'cfg', 'cfg: Configuration (CurrentVectorControllerCfg) as a struct', 'cfg'
    }, strjoin({ ...
    'disp(''CurrentVectorController'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''p_g_ref'');', ...
    'port_label(''input'', 3, ''q_g_ref'');', ...
    'port_label(''input'', 4, ''meas'');', ...
    'port_label(''input'', 5, ''u_c_ab'');', ...
    'port_label(''output'', 1, ''fbk'');', ...
    'port_label(''output'', 2, ''ref'');'}, newline)
    'CurrentVectorController/PLL', 'PLL (motulator)', 'Phase-locked loop with the filtered PCC voltage magnitude (PLL), giving the feedback signals fbk in its coordinates from the measurements and the realized converter voltage.', '', { ...
    'u_nom', 'u_nom: Nominal grid voltage (V), line-to-neutral peak value', 'cfg.u_nom'
    'w_nom', 'w_nom: Nominal grid angular frequency (rad/s)', 'cfg.w_nom'
    'alpha_pll', 'alpha_pll: PLL bandwidth (rad/s)', 'cfg.alpha_pll'
    'T_s', 'T_s: Sampling period (s)', 'cfg.T_s'
    }, strjoin({ ...
    'disp(''PLL'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''meas'');', ...
    'port_label(''input'', 3, ''u_c_ab'');', ...
    'port_label(''output'', 1, ''out'');'}, newline)
    'CurrentVectorController/CurrentLimiter', 'CurrentLimiter (motulator)', 'Current limiter (CurrentLimiter): the magnitude of the current reference is limited to i_max.', '', { ...
    'i_max', 'i_max: Maximum current (A), peak value', 'cfg.i_max'
    }, strjoin({ ...
    'disp(''CurrentLimiter'');', ...
    'port_label(''input'', 1, ''i'');', ...
    'port_label(''output'', 1, ''i_lim'');'}, newline)
    'CurrentVectorController/CurrentController', 'CurrentController (motulator)', '2DOF PI current controller (CurrentController) with the PCC voltage fbk.u_g as the feedforward. The inputs are the current reference and the feedback signals fbk (the current fbk.i_c and the PCC voltage fbk.u_g, and the realized voltage fbk.u_c and the angular speed fbk.w_c of the coordinates for the integral state), and the output is the voltage reference.', '', { ...
    'L', 'L: Filter inductance (H)', 'cfg.L'
    'alpha_c', 'alpha_c: Reference-tracking bandwidth (rad/s)', 'cfg.alpha_c'
    'alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_c', 'cfg.alpha_i'
    'T_s', 'T_s: Sampling period (s)', 'cfg.T_s'
    }, strjoin({ ...
    'disp(''CurrentController'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''i_c_ref'');', ...
    'port_label(''input'', 3, ''fbk'');', ...
    'port_label(''output'', 1, ''u_c'');'}, newline)
    };
s.control.sfunctions = { ...
    'get_measurement', 'double(T_s)'
    'PWM/compute_output', 'double(T_s), double(t_d), double(i_0), double(feedforward), double(d_min), double(mme)'
    'PWM/get_realized_voltage', 'double(T_s), double(t_d), double(i_0), double(feedforward), double(d_min), double(mme)'
    'CurrentVectorController/PLL', 'double(u_nom), double(w_nom), double(alpha_pll), double(T_s)'
    'CurrentVectorController/compute_output', 'double(cfg.T_s)'
    'CurrentVectorController/CurrentLimiter', 'double(i_max)'
    'CurrentVectorController/CurrentController', 'double(L), double(alpha_c), double(alpha_i), double(T_s)'
    'modulate', 'double(T_s)'
    'Monitored signals', 'double(T_s)'
    };
s.T_s = 'cfg.T_s';
s.t_stop = 0.08;

build_grid(s);
