% Build the Simulink model ipmsm_2kw_fvc.slx in the folder of this script.
% Generated by motulator_plecs.simulink.sm from motulator. The parameters of
% the control system are in the mask of the subsystem 'Flux-vector
% control', and those of the system model in the model workspace.
%
% The S-function is compiled with mex, which needs a C99 compiler with
% complex.h (gcc, clang, or MinGW-w64, not MSVC), see mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_plecs', 'simulink'));

s.name = 'ipmsm_2kw_fvc';
s.folder = here;
s.init = strjoin({ ...
    'machine.n_p = 3.0;', ...
    'machine.R_s = 3.6;', ...
    'machine.L_d = 0.036;', ...
    'machine.L_q = 0.051;', ...
    'machine.psi_f = 0.545;', ...
    'mechanics.J = 0.015;', ...
    'converter.u_dc = 540.0;'}, newline);
% {variable, prompt, tab, value}
s.mask = { ...
    'n_p', 'n_p: Number of pole pairs', 'Machine model (SynchronousMachinePars)', '3.0'
    'R_s', 'R_s: Stator resistance (Ohm)', 'Machine model (SynchronousMachinePars)', '3.6'
    'L_d', 'L_d: d-axis inductance (H)', 'Machine model (SynchronousMachinePars)', '0.036'
    'L_q', 'L_q: q-axis inductance (H)', 'Machine model (SynchronousMachinePars)', '0.051'
    'psi_f', 'psi_f: PM-flux linkage (Vs)', 'Machine model (SynchronousMachinePars)', '0.545'
    'i_s_max', 'i_s_max: Maximum stator current (A)', 'Flux-vector control (FluxVectorControllerCfg)', '6.5'
    'alpha_tau', 'alpha_tau: Torque-control bandwidth (rad/s)', 'Flux-vector control (FluxVectorControllerCfg)', '2*pi*100'
    'alpha_psi', 'alpha_psi: Flux-control bandwidth (rad/s), [] = alpha_tau', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_tau', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'alpha_o', 'alpha_o: Speed estimation pole (rad/s), [] = default', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'k_o', 'k_o: Observer gain [k0 k1], k_o(w_m) = k0 + k1*abs(w_m), [] = default', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'psi_s_min', 'psi_s_min: Minimum stator flux (Vs), [] = psi_f', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'psi_s_max', 'psi_s_max: Maximum stator flux (Vs)', 'Flux-vector control (FluxVectorControllerCfg)', 'inf'
    'k_u', 'k_u: Voltage utilization factor', 'Flux-vector control (FluxVectorControllerCfg)', '0.9'
    'k_mtpv', 'k_mtpv: MTPV margin', 'Flux-vector control (FluxVectorControllerCfg)', '0.85'
    'J', 'J: Inertia (kgm^2) for the speed observer, [] = not used', 'Flux-vector control (FluxVectorControllerCfg)', '[]'
    'sensorless', 'sensorless: Sensorless mode (1) or sensored mode (0)', 'Flux-vector control (FluxVectorControllerCfg)', '1.0'
    'T_s', 'T_s: Sampling period (s)', 'Flux-vector control (FluxVectorControllerCfg)', '0.000125'
    'speed_J', 'J: Total inertia (kgm^2)', 'Speed control (SpeedController)', '0.015'
    'speed_alpha_s', 'alpha_s: Reference-tracking bandwidth (rad/s)', 'Speed control (SpeedController)', '25.0'
    'speed_alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_s', 'Speed control (SpeedController)', '[]'
    'speed_tau_M_max', 'tau_M_max: Maximum motor torque (Nm)', 'Speed control (SpeedController)', 'inf'
    };
s.w_M_ref = [0.0999375 0.0 50.0];  % [time, before, after]
s.tau_L = [0.7 0.0 10.0];
s.T_s = 0.000125;
s.t_stop = 1.2;

build_sm_fvc(s);
