% Build the Simulink model im_2kw_vhz_open_loop.slx in the folder of this script.
% Generated by motulator_export.simulink from motulator. The parameters
% are defined by the script init_im_2kw_vhz_open_loop.m.
%
% The S-functions of the blocks of the control system are compiled with
% mex, which needs a C99 compiler with complex.h (gcc, clang, or
% MinGW-w64, not MSVC), see mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_export', 'simulink'));

s = struct();
s.folder = here;
s.name = 'im_2kw_vhz_open_loop';
s.init_script = 'init_im_2kw_vhz_open_loop';
s.machine = 'im';
s.enable = 1.0;
s.w_M_ref = [0.199875 0.0 157.07963267948966];
s.tau_L = [0.8 0.0 14.6];
s.scope = { ...
    'Speed', [7.0 8.0 4.0]
    'Torque', [9.0 10.0 6.0]
    'Current', [1.0 2.0 3.0]
    'Flux', [11.0 12.0 13.0]
    };
s.control.name = 'Observer-based VHz control';
s.control.sfunction = {'sfun_ovhz_get_measurement', 'sfun_ovhz_rate_limiter', 'sfun_ovhz_pwm', 'sfun_ovhz_pwm_realized_voltage', 'sfun_ovhz_flux_observer', 'sfun_ovhz_torque_filter', 'sfun_ovhz_reference_generator', 'sfun_ovhz_flux_torque_controller', 'sfun_ovhz_modulate', 'sfun_ovhz_monitored_signals'};
s.control.mask_type = 'VHzControlSystem (motulator)';
s.control.description = 'Observer-based V/Hz control of an induction machine drive, or pure open-loop V/Hz control if L_M = inf (VHzControlSystem with ObserverBasedVHzController). The speed reference is in mechanical rad/s. Each class of motulator is a block with a mask of its arguments. The top-level blocks refer to the variables of the model initialization, and the blocks inside them get their parameters as in the constructors of motulator. T_s is the sampling period of the measurements. While the input enable is not positive, the duty ratios are 0.5 and the state is reset to its initial value.';
s.control.mask = { ...
    'T_s', 'T_s: Sampling period (s)', 'VHzControlSystem', 'cfg.T_s'
    };
s.control.mask_init = '';
s.control.inputs = {'enable', 'w_M_ref', 'i_s_abc', 'u_dc'};
s.control.netlist.blocks = { ...
    'enable', 'Inport', [40.0 53.0 70.0 67.0], {'Port', '1'}
    'w_M_ref', 'Inport', [40.0 118.0 70.0 132.0], {'Port', '2'}
    'i_s_abc', 'Inport', [40.0 173.0 70.0 187.0], {'Port', '3'}
    'u_dc', 'Inport', [40.0 228.0 70.0 242.0], {'Port', '4'}
    'd_abc', 'Outport', [965.0 351.0 995.0 365.0], {'Port', '1'}
    'signals', 'Outport', [1695.0 273.0 1725.0 287.0], {'Port', '2'}
    'get_measurement', 'S-Function', [325.0 165.0 465.0 225.0], {'FunctionName', 'sfun_ovhz_get_measurement', 'Parameters', '1'}
    'RateLimiter', 'S-Function', [325.0 80.0 465.0 140.0], {'FunctionName', 'sfun_ovhz_rate_limiter', 'Parameters', '1, 1'}
    'PWM', 'Subsystem', [660.0 225.0 800.0 385.0], {'ContentPreviewEnabled', 'off'}
    'ObserverBasedVHzController', 'Subsystem', [965.0 50.0 1105.0 210.0], {'ContentPreviewEnabled', 'off'}
    'Goto w_M', 'Goto', [660.0 58.0 730.0 72.0], {'GotoTag', 'w_M', 'ShowName', 'off', 'TagVisibility', 'local'}
    'Goto fbk', 'Goto', [1180.0 38.0 1250.0 52.0], {'GotoTag', 'fbk', 'ShowName', 'off', 'TagVisibility', 'local'}
    'Goto ref', 'Goto', [1180.0 203.0 1250.0 217.0], {'GotoTag', 'ref', 'ShowName', 'off', 'TagVisibility', 'local'}
    'From fbk', 'From', [1180.0 258.0 1250.0 272.0], {'GotoTag', 'fbk', 'ShowName', 'off'}
    'From ref', 'From', [1180.0 313.0 1250.0 327.0], {'GotoTag', 'ref', 'ShowName', 'off'}
    'From w_M', 'From', [1180.0 368.0 1250.0 382.0], {'GotoTag', 'w_M', 'ShowName', 'off'}
    'ref.u_s', 'Selector', [1180.0 150.0 1230.0 180.0], {'NumberOfDimensions', '1', 'IndexOptions', 'Index vector (dialog)', 'Indices', '[3 4]', 'InputPortWidth', '4'}
    'modulate', 'S-Function', [1430.0 75.0 1570.0 135.0], {'FunctionName', 'sfun_ovhz_modulate', 'Parameters', '1'}
    'Monitored signals', 'S-Function', [1430.0 220.0 1570.0 340.0], {'FunctionName', 'sfun_ovhz_monitored_signals', 'Parameters', '1'}
    'Mux signals', 'Mux', [1648.0 220.0 1653.0 340.0], {'Inputs', '[2 2 3 2]', 'ShowName', 'off'}
    'From RateLimiter.enable', 'From', [230.0 88.0 300.0 102.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'From PWM.enable', 'From', [565.0 238.0 635.0 252.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'From ObserverBasedVHzController.enable', 'From', [870.0 63.0 940.0 77.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'From Monitored signals.enable', 'From', [1335.0 228.0 1405.0 242.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'Goto enable', 'Goto', [110.0 53.0 180.0 67.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    'PWM/enable', 'Inport', [40.0 243.0 70.0 257.0], {'Port', '1'}
    'PWM/meas', 'Inport', [40.0 78.0 70.0 92.0], {'Port', '2'}
    'PWM/u_c_ref_ab', 'Inport', [40.0 133.0 70.0 147.0], {'Port', '3'}
    'PWM/w', 'Inport', [40.0 188.0 70.0 202.0], {'Port', '4'}
    'PWM/u_c_ab', 'Outport', [845.0 55.0 875.0 69.0], {'Port', '1'}
    'PWM/u_c_zoh_ab', 'Outport', [845.0 113.0 875.0 127.0], {'Port', '2'}
    'PWM/d_abc', 'Outport', [845.0 153.0 875.0 167.0], {'Port', '3'}
    'PWM/compute_output', 'S-Function', [355.0 100.0 495.0 220.0], {'FunctionName', 'sfun_ovhz_pwm', 'Parameters', '1, 1, 1, 1, 1, 1'}
    'PWM/get_realized_voltage', 'S-Function', [645.0 40.0 785.0 130.0], {'FunctionName', 'sfun_ovhz_pwm_realized_voltage', 'Parameters', '1, 1, 1, 1, 1, 1'}
    'PWM/From compute_output.enable', 'From', [260.0 108.0 330.0 122.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'PWM/From get_realized_voltage.enable', 'From', [550.0 48.0 620.0 62.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'PWM/Goto enable', 'Goto', [110.0 243.0 180.0 257.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    'ObserverBasedVHzController/enable', 'Inport', [40.0 328.0 70.0 342.0], {'Port', '1'}
    'ObserverBasedVHzController/w_M', 'Inport', [40.0 273.0 70.0 287.0], {'Port', '2'}
    'ObserverBasedVHzController/meas', 'Inport', [40.0 183.0 70.0 197.0], {'Port', '3'}
    'ObserverBasedVHzController/u_c_ab', 'Inport', [40.0 218.0 70.0 232.0], {'Port', '4'}
    'ObserverBasedVHzController/fbk', 'Outport', [1420.0 198.0 1450.0 212.0], {'Port', '1'}
    'ObserverBasedVHzController/ref', 'Outport', [1420.0 123.0 1450.0 137.0], {'Port', '2'}
    'ObserverBasedVHzController/FluxObserver', 'S-Function', [355.0 145.0 495.0 265.0], {'FunctionName', 'sfun_ovhz_flux_observer', 'Parameters', '1, 1, 1, 1, 1, 1, 1, 1, 1'}
    'ObserverBasedVHzController/meas.u_dc', 'Selector', [555.0 40.0 605.0 70.0], {'NumberOfDimensions', '1', 'IndexOptions', 'Index vector (dialog)', 'Indices', '[3]', 'InputPortWidth', '3'}
    'ObserverBasedVHzController/fbk.tau_M', 'Selector', [555.0 130.0 605.0 160.0], {'NumberOfDimensions', '1', 'IndexOptions', 'Index vector (dialog)', 'Indices', '[9]', 'InputPortWidth', '19'}
    'ObserverBasedVHzController/tau_M_lpf', 'S-Function', [740.0 100.0 880.0 160.0], {'FunctionName', 'sfun_ovhz_torque_filter', 'Parameters', '1, 1'}
    'ObserverBasedVHzController/ReferenceGenerator', 'S-Function', [955.0 85.0 1095.0 175.0], {'FunctionName', 'sfun_ovhz_reference_generator', 'Parameters', '1, 1, 1, 1, 1, 1, 1, 1, 1, 1'}
    'ObserverBasedVHzController/FluxTorqueController', 'S-Function', [1170.0 115.0 1310.0 175.0], {'FunctionName', 'sfun_ovhz_flux_torque_controller', 'Parameters', '1, 1, 1, 1, 1, 1, 1'}
    'ObserverBasedVHzController/Mux ref', 'Mux', [1368.0 100.0 1373.0 160.0], {'Inputs', '[2 2]', 'ShowName', 'off'}
    'ObserverBasedVHzController/From FluxObserver.enable', 'From', [260.0 153.0 330.0 167.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'ObserverBasedVHzController/From tau_M_lpf.enable', 'From', [645.0 108.0 715.0 122.0], {'GotoTag', 'enable', 'ShowName', 'off'}
    'ObserverBasedVHzController/Goto enable', 'Goto', [110.0 328.0 180.0 342.0], {'GotoTag', 'enable', 'ShowName', 'off', 'TagVisibility', 'local'}
    };
s.control.netlist.aligns = { ...
    '', 'Goto fbk', 'Inport', 1.0, 'ObserverBasedVHzController', 'Outport', 1.0, -45.0
    '', 'modulate', 'Inport', 1.0, 'ObserverBasedVHzController', 'Outport', 1.0, 0.0
    '', 'RateLimiter', 'Outport', 1.0, 'ObserverBasedVHzController', 'Inport', 2.0, 0.0
    '', 'get_measurement', 'Outport', 1.0, 'ObserverBasedVHzController', 'Inport', 3.0, 45.0
    '', 'Goto w_M', 'Inport', 1.0, 'RateLimiter', 'Outport', 1.0, -45.0
    '', 'PWM', 'Inport', 2.0, 'get_measurement', 'Outport', 1.0, 90.0
    '', 'd_abc', 'Inport', 1.0, 'PWM', 'Outport', 3.0, 0.0
    '', 'ref.u_s', 'Outport', 1.0, 'modulate', 'Inport', 2.0, 45.0
    '', 'Goto ref', 'Inport', 1.0, 'ref.u_s', 'Inport', 1.0, 45.0
    '', 'Monitored signals', 'Inport', 2.0, 'From fbk', 'Outport', 1.0, 0.0
    '', 'Mux signals', 'Inport', 1.0, 'Monitored signals', 'Outport', 1.0, 0.0
    '', 'signals', 'Inport', 1.0, 'Mux signals', 'Outport', 1.0, 0.0
    '', 'w_M_ref', 'Outport', 1.0, 'RateLimiter', 'Inport', 2.0, 0.0
    '', 'From RateLimiter.enable', 'Outport', 1.0, 'RateLimiter', 'Inport', 1.0, 0.0
    '', 'From PWM.enable', 'Outport', 1.0, 'PWM', 'Inport', 1.0, 0.0
    '', 'From ObserverBasedVHzController.enable', 'Outport', 1.0, 'ObserverBasedVHzController', 'Inport', 1.0, 0.0
    '', 'From Monitored signals.enable', 'Outport', 1.0, 'Monitored signals', 'Inport', 1.0, 0.0
    '', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    'PWM', 'get_realized_voltage', 'Inport', 3.0, 'compute_output', 'Outport', 1.0, -45.0
    'PWM', 'u_c_ab', 'Inport', 1.0, 'get_realized_voltage', 'Outport', 1.0, 0.0
    'PWM', 'd_abc', 'Inport', 1.0, 'compute_output', 'Outport', 1.0, 0.0
    'PWM', 'meas', 'Outport', 1.0, 'get_realized_voltage', 'Inport', 2.0, 0.0
    'PWM', 'From compute_output.enable', 'Outport', 1.0, 'compute_output', 'Inport', 1.0, 0.0
    'PWM', 'From get_realized_voltage.enable', 'Outport', 1.0, 'get_realized_voltage', 'Inport', 1.0, 0.0
    'PWM', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    'ObserverBasedVHzController', 'FluxTorqueController', 'Inport', 1.0, 'ReferenceGenerator', 'Outport', 1.0, 0.0
    'ObserverBasedVHzController', 'Mux ref', 'Inport', 2.0, 'FluxTorqueController', 'Outport', 1.0, 0.0
    'ObserverBasedVHzController', 'ref', 'Inport', 1.0, 'Mux ref', 'Outport', 1.0, 0.0
    'ObserverBasedVHzController', 'FluxObserver', 'Outport', 1.0, 'ReferenceGenerator', 'Inport', 3.0, 45.0
    'ObserverBasedVHzController', 'meas.u_dc', 'Outport', 1.0, 'ReferenceGenerator', 'Inport', 1.0, -45.0
    'ObserverBasedVHzController', 'tau_M_lpf', 'Outport', 1.0, 'ReferenceGenerator', 'Inport', 2.0, 0.0
    'ObserverBasedVHzController', 'fbk', 'Inport', 1.0, 'FluxObserver', 'Outport', 1.0, 0.0
    'ObserverBasedVHzController', 'meas', 'Outport', 1.0, 'FluxObserver', 'Inport', 2.0, 0.0
    'ObserverBasedVHzController', 'fbk.tau_M', 'Outport', 1.0, 'tau_M_lpf', 'Inport', 2.0, 0.0
    'ObserverBasedVHzController', 'From FluxObserver.enable', 'Outport', 1.0, 'FluxObserver', 'Inport', 1.0, 0.0
    'ObserverBasedVHzController', 'From tau_M_lpf.enable', 'Outport', 1.0, 'tau_M_lpf', 'Inport', 1.0, 0.0
    'ObserverBasedVHzController', 'Goto enable', 'Inport', 1.0, 'enable', 'Outport', 1.0, 0.0
    };
s.control.netlist.lines = { ...
    '', 'From RateLimiter.enable/1', 'RateLimiter/1', []
    '', 'From PWM.enable/1', 'PWM/1', []
    '', 'From ObserverBasedVHzController.enable/1', 'ObserverBasedVHzController/1', []
    '', 'From Monitored signals.enable/1', 'Monitored signals/1', []
    '', 'w_M_ref/1', 'RateLimiter/2', []
    '', 'RateLimiter/1', 'ObserverBasedVHzController/2', []
    '', 'RateLimiter/1', 'Goto w_M/1', {'x', 490.0}
    '', 'i_s_abc/1', 'get_measurement/1', []
    '', 'u_dc/1', 'get_measurement/2', {'x', 200.0}
    '', 'get_measurement/1', 'PWM/2', {'x', 505.0}
    '', 'get_measurement/1', 'ObserverBasedVHzController/3', {'x', 825.0}
    '', 'PWM/1', 'ObserverBasedVHzController/4', {'x', 840.0}
    '', 'PWM/3', 'd_abc/1', []
    '', 'ObserverBasedVHzController/1', 'Goto fbk/1', {'x', 1130.0}
    '', 'ObserverBasedVHzController/1', 'modulate/1', []
    '', 'ObserverBasedVHzController/2', 'Goto ref/1', {'x', 1145.0}
    '', 'ObserverBasedVHzController/2', 'ref.u_s/1', {'x', 1145.0}
    '', 'ref.u_s/1', 'modulate/2', {'x', 1290.0}
    '', 'modulate/1', 'PWM/3', {'x', 1610.0, 'y', 440.0, 'x', 520.0}
    '', 'modulate/2', 'PWM/4', {'x', 1595.0, 'y', 425.0, 'x', 535.0}
    '', 'From fbk/1', 'Monitored signals/2', []
    '', 'From ref/1', 'Monitored signals/3', {'x', 1275.0}
    '', 'From w_M/1', 'Monitored signals/4', {'x', 1305.0}
    '', 'Monitored signals/1', 'Mux signals/1', []
    '', 'Monitored signals/2', 'Mux signals/2', []
    '', 'Monitored signals/3', 'Mux signals/3', []
    '', 'Monitored signals/4', 'Mux signals/4', []
    '', 'Mux signals/1', 'signals/1', []
    '', 'enable/1', 'Goto enable/1', []
    'PWM', 'From compute_output.enable/1', 'compute_output/1', []
    'PWM', 'From get_realized_voltage.enable/1', 'get_realized_voltage/1', []
    'PWM', 'meas/1', 'compute_output/2', {'x', 230.0}
    'PWM', 'meas/1', 'get_realized_voltage/2', []
    'PWM', 'u_c_ref_ab/1', 'compute_output/3', {'x', 215.0}
    'PWM', 'w/1', 'compute_output/4', {'x', 200.0}
    'PWM', 'compute_output/1', 'd_abc/1', []
    'PWM', 'compute_output/1', 'get_realized_voltage/3', {'x', 520.0}
    'PWM', 'get_realized_voltage/1', 'u_c_ab/1', []
    'PWM', 'get_realized_voltage/2', 'u_c_zoh_ab/1', {'x', 810.0}
    'PWM', 'enable/1', 'Goto enable/1', []
    'ObserverBasedVHzController', 'From FluxObserver.enable/1', 'FluxObserver/1', []
    'ObserverBasedVHzController', 'From tau_M_lpf.enable/1', 'tau_M_lpf/1', []
    'ObserverBasedVHzController', 'meas/1', 'FluxObserver/2', []
    'ObserverBasedVHzController', 'u_c_ab/1', 'FluxObserver/3', {'x', 200.0}
    'ObserverBasedVHzController', 'w_M/1', 'FluxObserver/4', {'x', 215.0}
    'ObserverBasedVHzController', 'meas/1', 'meas.u_dc/1', {'x', 230.0}
    'ObserverBasedVHzController', 'FluxObserver/1', 'fbk.tau_M/1', {'x', 520.0}
    'ObserverBasedVHzController', 'FluxObserver/1', 'ReferenceGenerator/3', {'x', 905.0}
    'ObserverBasedVHzController', 'FluxObserver/1', 'FluxTorqueController/2', {'x', 1120.0}
    'ObserverBasedVHzController', 'FluxObserver/1', 'fbk/1', []
    'ObserverBasedVHzController', 'fbk.tau_M/1', 'tau_M_lpf/2', []
    'ObserverBasedVHzController', 'meas.u_dc/1', 'ReferenceGenerator/1', {'x', 920.0}
    'ObserverBasedVHzController', 'tau_M_lpf/1', 'ReferenceGenerator/2', []
    'ObserverBasedVHzController', 'ReferenceGenerator/1', 'FluxTorqueController/1', []
    'ObserverBasedVHzController', 'ReferenceGenerator/1', 'Mux ref/1', {'x', 1135.0, 'y', 75.0, 'x', 1335.0}
    'ObserverBasedVHzController', 'FluxTorqueController/1', 'Mux ref/2', []
    'ObserverBasedVHzController', 'Mux ref/1', 'ref/1', []
    'ObserverBasedVHzController', 'enable/1', 'Goto enable/1', []
    };
s.control.netlist.masks = { ...
    'RateLimiter', 'RateLimiter (motulator)', 'Rate limiter (RateLimiter): the rising and falling rates of the signal are limited to rate_limit, e.g., the slew rate of the speed reference (mechanical rad/s²) in VHzControlSystem.', '', { ...
    'rate_limit', 'rate_limit: Rate limit, inf = none', 'slew_rate'
    'T_s', 'T_s: Sampling period (s)', 'T_s'
    }, strjoin({ ...
    'disp(''RateLimiter'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''u'');', ...
    'port_label(''output'', 1, ''y'');'}, newline)
    'PWM', 'PWM (motulator)', 'Space-vector PWM with the minimum-phase-error (MPE) or the minimum-magnitude-error (MME) overmodulation (PWM), with the duty-ratio error model d_err = dead_time_error(i_abc, d_abc, t_d, T_s, sign) and its compensation, and the minimum pulses. The blocks inside are its methods compute_output and get_realized_voltage.', strjoin({ ...
    '% MME overmodulation, or MPE', ...
    'mme = strcmp(overmodulation, ''MME'');'}, newline), { ...
    'T_s', 'T_s: Sampling period (s)', 'T_s'
    't_d', 't_d: Dead time (s) in d_err = dead_time_error(i_abc, d_abc, t_d, T_s), 0 = None', 'pwm.t_d'
    'i_0', 'i_0: Current scale (A) of sign = tanh(i/i_0) in dead_time_error, 0 = np.sign', 'pwm.i_0'
    'feedforward', 'feedforward: Compensate for d_err (1) or not (0)', 'pwm.feedforward'
    'd_min', 'd_min: Minimum duty ratio of a switching leg, 0 = no limit', 'pwm.d_min'
    'overmodulation', 'overmodulation: Overmodulation, ''MPE'' or ''MME''', 'pwm.overmodulation'
    }, strjoin({ ...
    'disp(''PWM'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''meas'');', ...
    'port_label(''input'', 3, ''u_c_ref_ab'');', ...
    'port_label(''input'', 4, ''w'');', ...
    'port_label(''output'', 1, ''u_c_ab'');', ...
    'port_label(''output'', 2, ''u_c_zoh_ab'');', ...
    'port_label(''output'', 3, ''d_abc'');'}, newline)
    'ObserverBasedVHzController', 'ObserverBasedVHzController (motulator)', 'Observer-based V/Hz controller (ObserverBasedVHzController), or pure open-loop V/Hz control if par.L_M = inf. The configuration cfg is a struct with the fields of ObserverBasedVHzControllerCfg ([] = None, i.e., the default; the default observer gain k_o only). The mask initialization passes the parameters to the blocks inside it, as ObserverBasedVHzController. The block tau_M_lpf is the low-pass filter of the torque estimate, whose output is the torque reference. The machine model par is a struct with the fields n_p, R_s, R_R, L_sgm, and L_M of InductionMachineInvGammaPars.', strjoin({ ...
    '% Pure open-loop V/Hz control with L_M = inf (ObserverBasedVHzController):', ...
    '% the unit observer gain with the weight h = 1, which disables the model-based', ...
    '% correction (create_vhz_observer), the initial flux estimate, and k_u = inf', ...
    'if isinf(par.L_M)', ...
    '  k_o = 1;', ...
    '  h = 1;', ...
    '  psi_s0 = cfg.psi_s_nom;', ...
    '  k_u = inf;', ...
    'else', ...
    '  k_o = [];', ...
    '  h = 0;', ...
    '  psi_s0 = 0;', ...
    '  k_u = cfg.k_u;', ...
    'end'}, newline), { ...
    'par', 'par: Machine model (InductionMachineInvGammaPars) as a struct', 'par'
    'cfg', 'cfg: Configuration (ObserverBasedVHzControllerCfg) as a struct', 'cfg'
    }, strjoin({ ...
    'disp(''ObserverBasedVHzController'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''w_M'');', ...
    'port_label(''input'', 3, ''meas'');', ...
    'port_label(''input'', 4, ''u_c_ab'');', ...
    'port_label(''output'', 1, ''fbk'');', ...
    'port_label(''output'', 2, ''ref'');'}, newline)
    'ObserverBasedVHzController/FluxObserver', 'FluxObserver (motulator)', 'Reduced-order flux observer in synchronous coordinates (FluxObserver), created by create_vhz_observer: the rotor speed w_M is the rate-limited speed reference, and the external speed error signal is zero, with the weight h (1 in pure open-loop V/Hz control, which disables the model-based correction). The initial stator flux estimate is psi_s0. The machine model par is a struct with the fields n_p, R_s, R_R, L_sgm, and L_M of InductionMachineInvGammaPars. L_M = inf in pure open-loop V/Hz control.', strjoin({ ...
    '% Fields of the machine model par (InductionMachineInvGammaPars) for the', ...
    '% C-Script', ...
    'par_n_p = par.n_p;', ...
    'par_R_s = par.R_s;', ...
    'par_R_R = par.R_R;', ...
    'par_L_sgm = par.L_sgm;', ...
    'par_L_M = par.L_M;'}, newline), { ...
    'par', 'par: Machine model (InductionMachineInvGammaPars) as a struct', 'par'
    'k_o', 'k_o: Observer gain k_o(w_m), [] = the default of create_vhz_observer, 1 = unity', 'k_o'
    'h', 'h: Weight of the external speed error signal', 'h'
    'psi_s0', 'psi_s0: Initial stator flux estimate (Vs)', 'psi_s0'
    'T_s', 'T_s: Sampling period (s)', 'T_s'
    }, strjoin({ ...
    'disp(''FluxObserver'');', ...
    'port_label(''input'', 1, ''enable'');', ...
    'port_label(''input'', 2, ''meas'');', ...
    'port_label(''input'', 3, ''u_s_ab'');', ...
    'port_label(''input'', 4, ''w_M'');', ...
    'port_label(''output'', 1, ''out'');'}, newline)
    'ObserverBasedVHzController/ReferenceGenerator', 'ReferenceGenerator (motulator)', 'Reference generator with field weakening and torque limits (ReferenceGenerator). The inputs are the DC-bus voltage, the torque reference, and the feedback signals fbk (the synchronous angular frequency fbk.w_s and the rotor flux estimate fbk.psi_R). The output ref is [psi_s tau_M], the flux reference and the limited torque reference. The machine model par is a struct with the fields n_p, R_s, R_R, L_sgm, and L_M of InductionMachineInvGammaPars. L_M = inf in pure open-loop V/Hz control.', strjoin({ ...
    '% Fields of the machine model par (InductionMachineInvGammaPars) for the', ...
    '% C-Script', ...
    'par_n_p = par.n_p;', ...
    'par_R_s = par.R_s;', ...
    'par_R_R = par.R_R;', ...
    'par_L_sgm = par.L_sgm;', ...
    'par_L_M = par.L_M;'}, newline), { ...
    'par', 'par: Machine model (InductionMachineInvGammaPars) as a struct', 'par'
    'psi_s_nom', 'psi_s_nom: Nominal stator flux linkage (Vs)', 'cfg.psi_s_nom'
    'i_s_max', 'i_s_max: Maximum stator current (A)', 'cfg.i_s_max'
    'tau_M_max', 'tau_M_max: Maximum torque reference (Nm)', 'inf'
    'k_u', 'k_u: Voltage utilization factor', 'k_u'
    'k_b', 'k_b: Breakdown torque margin', 'cfg.k_b'
    }, strjoin({ ...
    'disp(''ReferenceGenerator'');', ...
    'port_label(''input'', 1, ''u_dc'');', ...
    'port_label(''input'', 2, ''tau_M_ref'');', ...
    'port_label(''input'', 3, ''fbk'');', ...
    'port_label(''output'', 1, ''ref'');'}, newline)
    'ObserverBasedVHzController/FluxTorqueController', 'FluxTorqueController (motulator)', 'Flux and torque controller (FluxTorqueController) without the integral action. The input ref is [psi_s tau_M], the flux and torque references, and the output is the stator voltage reference. The machine model par is a struct with the fields n_p, R_s, R_R, L_sgm, and L_M of InductionMachineInvGammaPars. L_M = inf in pure open-loop V/Hz control.', strjoin({ ...
    '% Fields of the machine model par (InductionMachineInvGammaPars) for the', ...
    '% C-Script', ...
    'par_n_p = par.n_p;', ...
    'par_R_s = par.R_s;', ...
    'par_R_R = par.R_R;', ...
    'par_L_sgm = par.L_sgm;', ...
    'par_L_M = par.L_M;'}, newline), { ...
    'par', 'par: Machine model (InductionMachineInvGammaPars) as a struct', 'par'
    'alpha_psi', 'alpha_psi: Flux-control bandwidth (rad/s)', 'cfg.alpha_psi'
    'alpha_tau', 'alpha_tau: Torque-control bandwidth (rad/s)', 'cfg.alpha_tau'
    }, strjoin({ ...
    'disp(''FluxTorqueController'');', ...
    'port_label(''input'', 1, ''ref'');', ...
    'port_label(''input'', 2, ''fbk'');', ...
    'port_label(''output'', 1, ''u_s'');'}, newline)
    };
s.control.sfunctions = { ...
    'get_measurement', 'double(T_s)'
    'RateLimiter', 'double(rate_limit), double(T_s)'
    'PWM/compute_output', 'double(T_s), double(t_d), double(i_0), double(feedforward), double(d_min), double(mme)'
    'PWM/get_realized_voltage', 'double(T_s), double(t_d), double(i_0), double(feedforward), double(d_min), double(mme)'
    'ObserverBasedVHzController/FluxObserver', 'double(k_o), double(h), double(psi_s0), double(T_s), double(par_n_p), double(par_R_s), double(par_R_R), double(par_L_sgm), double(par_L_M)'
    'ObserverBasedVHzController/tau_M_lpf', 'double(cfg.alpha_f), double(cfg.T_s)'
    'ObserverBasedVHzController/ReferenceGenerator', 'double(psi_s_nom), double(i_s_max), double(tau_M_max), double(k_u), double(k_b), double(par_n_p), double(par_R_s), double(par_R_R), double(par_L_sgm), double(par_L_M)'
    'ObserverBasedVHzController/FluxTorqueController', 'double(alpha_psi), double(alpha_tau), double(par_n_p), double(par_R_s), double(par_R_R), double(par_L_sgm), double(par_L_M)'
    'modulate', 'double(T_s)'
    'Monitored signals', 'double(T_s)'
    };
s.T_s = 'cfg.T_s';
s.t_stop = 1.6;

build_drive(s);
