% Build the Simulink model im_2kw_cvc.slx in the folder of this script.
% Generated by motulator_plecs.simulink from motulator. The parameters of
% the control system are in the mask of the subsystem 'Current-vector control',
% and those of the system model in the model workspace.
%
% The S-function sfun_current_vector_control.c is compiled with mex, which needs a C99
% compiler with complex.h (gcc, clang, or MinGW-w64, not MSVC), see
% mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_plecs', 'simulink'));

s = struct();
s.folder = here;
s.name = 'im_2kw_cvc';
s.init = strjoin({ ...
    'machine.n_p = 2.0;', ...
    'machine.R_s = 3.7;', ...
    'machine.R_R = 2.1;', ...
    'machine.L_sgm = 0.021;', ...
    'machine.L_M = 0.224;', ...
    'mechanics.J = 0.015;', ...
    'converter.u_dc = 540.0;'}, newline);
s.machine = 'im';
s.w_M_ref = [0.2000625 0.0 78.53981633974483];
s.tau_L = [0.75 0.0 14.6];
s.scope = { ...
    'Speed', [7.0 8.0 4.0]
    'Torque', [9.0 10.0 6.0]
    'Current', [1.0 2.0 3.0]
    'Flux', [11.0 12.0]
    };
s.control.name = 'Current-vector control';
s.control.sfunction = 'sfun_current_vector_control';
s.control.mask_type = 'Current-vector control (motulator)';
s.control.description = 'Speed control of an induction machine drive with current-vector control. The parameters correspond to the motulator API: InductionMachineInvGammaPars, CurrentVectorControllerCfg, and SpeedController. Empty parameters ([]) correspond to None, i.e., the defaults of motulator.';
s.control.mask = { ...
    'n_p', 'n_p: Number of pole pairs', 'Machine model (InductionMachineInvGammaPars)', '2.0'
    'R_s', 'R_s: Stator resistance (Ohm)', 'Machine model (InductionMachineInvGammaPars)', '3.7'
    'R_R', 'R_R: Rotor resistance (Ohm)', 'Machine model (InductionMachineInvGammaPars)', '2.1'
    'L_sgm', 'L_sgm: Leakage inductance (H)', 'Machine model (InductionMachineInvGammaPars)', '0.021'
    'L_M', 'L_M: Magnetizing inductance (H)', 'Machine model (InductionMachineInvGammaPars)', '0.224'
    'psi_s_nom', 'psi_s_nom: Nominal stator flux linkage (Vs)', 'Current-vector control (CurrentVectorControllerCfg)', '1.0395957349782348'
    'i_s_max', 'i_s_max: Maximum stator current (A)', 'Current-vector control (CurrentVectorControllerCfg)', '10.606601717798213'
    'alpha_c', 'alpha_c: Current-control bandwidth (rad/s)', 'Current-vector control (CurrentVectorControllerCfg)', '2*pi*200'
    'alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_c', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'alpha_o', 'alpha_o: Speed estimation pole (rad/s), [] = default', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'w_s_nom', 'w_s_nom: Nominal stator angular frequency (rad/s)', 'Current-vector control (CurrentVectorControllerCfg)', '2*pi*50'
    'k_u', 'k_u: Voltage utilization factor', 'Current-vector control (CurrentVectorControllerCfg)', '0.95'
    'k_fw', 'k_fw: Field-weakening gain (1/H), [] = default', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'J', 'J: Inertia (kgm^2) for the speed observer, [] = not used', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'sensorless', 'sensorless: Sensorless mode (1) or sensored mode (0)', 'Current-vector control (CurrentVectorControllerCfg)', '1.0'
    'T_s', 'T_s: Sampling period (s)', 'Current-vector control (CurrentVectorControllerCfg)', '0.000125'
    'speed_J', 'J: Total inertia (kgm^2)', 'Speed control (SpeedController)', '0.015'
    'speed_alpha_s', 'alpha_s: Reference-tracking bandwidth (rad/s)', 'Speed control (SpeedController)', '2*pi*4'
    'speed_alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_s', 'Speed control (SpeedController)', '[]'
    'speed_tau_M_max', 'tau_M_max: Maximum motor torque (Nm)', 'Speed control (SpeedController)', 'inf'
    };
s.control.mask_init = '';
s.control.params = {'double(n_p)', 'double(R_s)', 'double(R_R)', 'double(L_sgm)', 'double(L_M)', 'double(psi_s_nom)', 'double(i_s_max)', 'double(alpha_c)', 'double(alpha_i)', 'double(alpha_o)', 'double(w_s_nom)', 'double(k_u)', 'double(k_fw)', 'double(J)', 'double(sensorless)', 'double(T_s)', 'double(speed_J)', 'double(speed_alpha_s)', 'double(speed_alpha_i)', 'double(speed_tau_M_max)'};
s.control.inputs = {'w_M_ref', 'i_s_abc', 'u_dc', 'w_M'};
s.control.outputs = {'d_abc', 'Speed (w_M_ref, w_M)', 'Torque (tau_M_ref, tau_M)', 'Flux linkage (psi_s, psi_R)', 'Current (i_sd_ref, i_sd, i_sq_ref, i_sq)'};
s.T_s = 0.000125;
s.t_stop = 1.5;

build_drive(s);
