%INIT_IM_2KW_VHZ_OPEN_LOOP Parameters of the Simulink model im_2kw_vhz_open_loop.
%   Generated by motulator_export.simulink from motulator. The model
%   runs this script after loading and at the start of each simulation.
%   The blocks of the control system have masks of the arguments of
%   their classes, which refer to the structs of the control system
%   below, as in the motulator API.

%% System model
machine.n_p = 2;
machine.R_s = 3.7;
machine.R_R = 2.1;
machine.L_sgm = 0.021;
machine.L_M = 0.224;
mechanics.J = 0.015;
converter.u_dc = 540;

%% Control system ([] = None, the default)
% Machine model of the control system (InductionMachineInvGammaPars, L_M = inf: pure open-loop V/Hz control)
par.n_p = 2;
par.R_s = 0;
par.R_R = 0;
par.L_sgm = 0;
par.L_M = inf;
% Observer-based V/Hz control (ObserverBasedVHzControllerCfg)
cfg.psi_s_nom = 1.0395957349782348;
cfg.i_s_max = inf;
cfg.alpha_psi = 0;
cfg.alpha_tau = 0;
cfg.alpha_f = 0;
cfg.k_u = 0.9;
cfg.k_b = 0.9;
cfg.T_s = 0.00025;
% Slew rate of the speed reference (VHzControlSystem), mechanical rad/s^2
slew_rate = 2*pi*60;
% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,
% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its
% compensation, the minimum duty ratio of a switching leg, and the
% overmodulation ('MPE' or 'MME')
pwm.t_d = 0;
pwm.i_0 = 0;
pwm.feedforward = 1;
pwm.d_min = 0;
pwm.overmodulation = 'MME';
