%INIT_IM_2KW_CVC Parameters of the Simulink model im_2kw_cvc.
%   Generated by motulator_export.simulink from motulator. The model
%   runs this script after loading and at the start of each simulation.
%   The blocks of the control system have masks of the arguments of
%   their classes, which refer to the structs of the control system
%   below, as in the motulator API.

%% System model
machine.n_p = 2;
machine.R_s = 3.7;
machine.R_R = 2.1;
machine.L_sgm = 0.021;
machine.L_M = 0.224;
mechanics.J = 0.015;
converter.u_dc = 540;

%% Control system ([] = None, the default)
% Machine model of the control system (InductionMachineInvGammaPars)
par.n_p = 2;
par.R_s = 3.7;
par.R_R = 2.1;
par.L_sgm = 0.021;
par.L_M = 0.224;
% Current-vector control (CurrentVectorControllerCfg)
cfg.psi_s_nom = 1.0395957349782348;
cfg.i_s_max = 10.606601717798213;
cfg.alpha_c = 2*pi*200;
cfg.alpha_i = [];
cfg.alpha_o = [];
cfg.w_s_nom = 2*pi*50;
cfg.k_u = 0.95;
cfg.k_fw = [];
cfg.J = [];
cfg.sensorless = 1;
cfg.T_s = 0.000125;
% Speed controller (SpeedController)
speed_ctrl.J = 0.015;
speed_ctrl.alpha_s = 2*pi*4;
speed_ctrl.alpha_i = [];
speed_ctrl.tau_M_max = inf;
% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,
% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its
% compensation, the minimum duty ratio of a switching leg, and the
% overmodulation ('MPE' or 'MME')
pwm.t_d = 0;
pwm.i_0 = 0;
pwm.feedforward = 1;
pwm.d_min = 0;
pwm.overmodulation = 'MPE';
