%INIT_IPMSM_2KW_FVC Parameters of the Simulink model ipmsm_2kw_fvc.
%   Generated by motulator_export.simulink from motulator. The model
%   runs this script after loading and at the start of each simulation.
%   The blocks of the control system have masks of the arguments of
%   their classes, which refer to the structs of the control system
%   below, as in the motulator API.

%% System model
machine.n_p = 3;
machine.R_s = 3.6;
machine.L_d = 0.036;
machine.L_q = 0.051;
machine.psi_f = 0.545;
mechanics.J = 0.015;
converter.u_dc = 540;

%% Control system ([] = None, the default)
% Machine model of the control system (SynchronousMachinePars)
par.n_p = 3;
par.R_s = 3.6;
par.L_d = 0.036;
par.L_q = 0.051;
par.psi_f = 0.545;
% Flux-vector control (FluxVectorControllerCfg)
cfg.i_s_max = 6.5;
cfg.alpha_tau = 2*pi*100;
cfg.alpha_psi = [];
cfg.alpha_i = [];
cfg.alpha_o = [];
cfg.k_o = [];
cfg.k_f = [];
cfg.psi_s_min = [];
cfg.psi_s_max = inf;
cfg.k_u = 0.9;
cfg.k_mtpv = 0.85;
cfg.J = [];
cfg.sensorless = 1;
cfg.T_s = 0.000125;
% Speed controller (SpeedController)
speed_ctrl.J = 0.015;
speed_ctrl.alpha_s = 25;
speed_ctrl.alpha_i = [];
speed_ctrl.tau_M_max = inf;
% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,
% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its
% compensation, the minimum duty ratio of a switching leg, and the
% overmodulation ('MPE' or 'MME')
pwm.t_d = 0;
pwm.i_0 = 0;
pwm.feedforward = 1;
pwm.d_min = 0;
pwm.overmodulation = 'MPE';
