%INIT_GFL_10KVA_LCL Parameters of the Simulink model gfl_10kva_lcl.
%   Generated by motulator_export.simulink from motulator. The model
%   runs this script after loading and at the start of each simulation.
%   The blocks of the control system have masks of the arguments of
%   their classes, which refer to the structs of the control system
%   below, as in the motulator API.

%% System model
converter.u_dc = 650;
ac_filter.L_fc = 0.003700874424440534;
ac_filter.L_fg = 0.003700874424440534;
ac_filter.C_f = 8.593839157387184e-06;
ac_filter.u_f0_ab = [326.5986323710904 0.0];
ac_source.e_g = 326.5986323710904;
ac_source.w_g = 2*pi*50;

%% Control system ([] = None, the default)
% Grid-following control (CurrentVectorControllerCfg)
cfg.i_max = 30.75914498161482;
cfg.L = 0.003700874424440534;
cfg.alpha_c = 2*pi*400;
cfg.alpha_i = 2*pi*400;
cfg.u_nom = 326.5986323710904;
cfg.w_nom = 2*pi*50;
cfg.alpha_pll = 2*pi*20;
cfg.T_s = 0.0001;
% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,
% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its
% compensation, the minimum duty ratio of a switching leg, and the
% overmodulation ('MPE' or 'MME')
pwm.t_d = 0;
pwm.i_0 = 0;
pwm.feedforward = 1;
pwm.d_min = 0;
pwm.overmodulation = 'MPE';
