%INIT_GFM_13KVA_DO Parameters of the Simulink model gfm_13kva_do.
%   Generated by motulator_export.simulink from motulator. The model
%   runs this script after loading and at the start of each simulation.
%   The blocks of the control system have masks of the arguments of
%   their classes, which refer to the structs of the control system
%   below, as in the motulator API.

%% System model
converter.u_dc = 650;
ac_filter.L_f = 0.006125876615797688;
ac_filter.R_f = 0.6415002990995841;
ac_filter.L_g = 0.030220991304601926;
ac_source.e_g = 326.5986323710904;
ac_source.w_g = 2*pi*50;

%% Control system ([] = None, the default)
% Grid-forming control (ObserverBasedGridFormingControllerCfg)
cfg.i_max = 33.09259735953043;
cfg.L = 0.014293712103527936;
cfg.R = 0.6415002990995841;
cfg.R_a = 2.5660011963983362;
cfg.k_v = [];
cfg.alpha_o = 2*pi*50;
cfg.alpha_c = 2*pi*400;
cfg.u_nom = 326.5986323710904;
cfg.w_nom = 2*pi*50;
cfg.i_d_max = [];
cfg.alpha_l = 2*pi*50;
cfg.T_s = 0.000125;
% PWM: the duty-ratio error model d_err = dead_time_error(i_abc, d_abc,
% t_d, cfg.T_s, sign) with sign = tanh(i/i_0) (np.sign if i_0 = 0), its
% compensation, the minimum duty ratio of a switching leg, and the
% overmodulation ('MPE' or 'MME')
pwm.t_d = 0;
pwm.i_0 = 0;
pwm.feedforward = 1;
pwm.d_min = 0;
pwm.overmodulation = 'MPE';
