/*
 * sfun_gfm_monitored_signals: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_gfm_monitored_signals.c
 */

#define S_FUNCTION_NAME sfun_gfm_monitored_signals
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export: a block of the control system. The
 * parameters come from its mask. */
#include "common.c"
#include "gfm_observer.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)


/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 12, 6};
static const int FEEDTHROUGH[] = {1, 1, 1};
static const int OUTPUT_WIDTHS[] = {3, 2, 4, 1};
#define NUM_INPUTS 3
#define NUM_OUTPUTS 4
#define NUM_PARAMS 1

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(0, 0) * ParamDim(0, 1) != 1
        || !(ParamRealData(0, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(0, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: the algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 3; k++) {
            OutputSignal(0, k) = 0.0;
        }
        for (int k = 0; k < 2; k++) {
            OutputSignal(1, k) = 0.0;
        }
        for (int k = 0; k < 4; k++) {
            OutputSignal(2, k) = 0.0;
        }
        for (int k = 0; k < 1; k++) {
            OutputSignal(3, k) = 0.0;
        }
        return;
    }

    double fbk_u[FBK_WIDTH];
    for (int k = 0; k < FBK_WIDTH; k++) {
        fbk_u[k] = InputSignal(1, k);
    }
    GFMFeedbacks fbk;
    gfm_feedbacks_unpack(fbk_u, &fbk);
    double ref_u[REF_WIDTH];
    for (int k = 0; k < REF_WIDTH; k++) {
        ref_u[k] = InputSignal(2, k);
    }
    GFMReferences ref;
    gfm_references_unpack(ref_u, &ref);
    /* Monitored signals */
    OutputSignal(0, 0) = ref.p_g;
    OutputSignal(0, 1) = fbk.p_g;
    OutputSignal(0, 2) = fbk.q_g;
    OutputSignal(1, 0) = ref.v_c;
    OutputSignal(1, 1) = cabs(fbk.v_c);
    OutputSignal(2, 0) = creal(ref.i_c);
    OutputSignal(2, 1) = creal(fbk.i_c);
    OutputSignal(2, 2) = cimag(ref.i_c);
    OutputSignal(2, 3) = cimag(fbk.i_c);
    OutputSignal(3, 0) = fbk.theta_c;
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
