/*
 * sfun_gfl_pwm_realized_voltage: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_gfl_pwm_realized_voltage.c
 */

#define S_FUNCTION_NAME sfun_gfl_pwm_realized_voltage
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export: a block of the control system. The
 * parameters come from its mask. */
#include "common.c"
#include "gfl_current_vector.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

static PWM self;

/* Initial state, restored while the block is disabled */
static PWM self_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 5, 3};
static const int FEEDTHROUGH[] = {1, 1, 0};
static const int OUTPUT_WIDTHS[] = {2, 2};
#define NUM_INPUTS 3
#define NUM_OUTPUTS 2
#define NUM_PARAMS 6

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(0, 0) * ParamDim(0, 1) != 1
        || !(ParamRealData(0, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(0, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    if (PDIM(0) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }
    if (PDIM(1) != 1) {
        SetErrorMessage("t_d must be a scalar.");
        return;
    }
    if (PDIM(2) != 1) {
        SetErrorMessage("i_0 must be a scalar.");
        return;
    }
    if (PDIM(3) != 1) {
        SetErrorMessage("feedforward must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("d_min must be a scalar.");
        return;
    }
    if (PDIM(5) != 1) {
        SetErrorMessage("mme must be a scalar.");
        return;
    }
    pwm_init(&self, 1.5);
    pwm_set_overmodulation(&self, (int)P(5, 0));
    pwm_set_dead_time(&self, P(1, 0), P(0, 0), P(2, 0), (int)P(3, 0));
    pwm_set_min_pulse(&self, P(4, 0));

    self_init = self;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: the algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 2; k++) {
            OutputSignal(0, k) = 0.0;
        }
        for (int k = 0; k < 2; k++) {
            OutputSignal(1, k) = 0.0;
        }
        return;
    }

    double meas_u[MEAS_WIDTH];
    for (int k = 0; k < MEAS_WIDTH; k++) {
        meas_u[k] = InputSignal(1, k);
    }
    GridMeasurements meas;
    grid_measurements_unpack(meas_u, &meas);
    /* Average of the previous and the ongoing periods, and of the
     * ongoing period */
    double complex u_c_ab =
        pwm_realized_voltage(&self, meas.i_c_ab, meas.u_dc, 1);
    double complex u_c_zoh_ab =
        pwm_realized_voltage(&self, meas.i_c_ab, meas.u_dc, 0);
    OutputSignal(0, 0) = creal(u_c_ab);
    OutputSignal(0, 1) = cimag(u_c_ab);
    OutputSignal(1, 0) = creal(u_c_zoh_ab);
    OutputSignal(1, 1) = cimag(u_c_zoh_ab);
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        self = self_init;
        return;
    }

    /* The duty ratios of the next period */
    double d_abc[3];
    for (int k = 0; k < 3; k++) {
        d_abc[k] = InputSignal(2, k);
    }
    pwm_update(&self, d_abc);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
