/*
 * sfun_gfm_current_reference: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_gfm_current_reference.c
 */

#define S_FUNCTION_NAME sfun_gfm_current_reference
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export: a block of the control system. The
 * parameters come from its mask. */
#include "common.c"
#include "gfm_observer.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

static GFMController self;
static double T_s; /* Sampling period */
static GFMFeedbacks fbk;

/* Initial state, restored while the block is disabled */
static GFMController self_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 1, 1, 2, 12};
static const int FEEDTHROUGH[] = {1, 1, 1, 0, 1};
static const int OUTPUT_WIDTHS[] = {1, 1, 2};
#define NUM_INPUTS 5
#define NUM_OUTPUTS 3
#define NUM_PARAMS 7

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(6, 0) * ParamDim(6, 1) != 1
        || !(ParamRealData(6, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(6, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    if (PDIM(0) != 1) {
        SetErrorMessage("R_a must be a scalar.");
        return;
    }
    if (PDIM(1) != 1) {
        SetErrorMessage("k_v must be a scalar.");
        return;
    }
    if (PDIM(2) != 1) {
        SetErrorMessage("k_c must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("alpha_l must be a scalar.");
        return;
    }
    if (PDIM(5) != 1) {
        SetErrorMessage("u_nom must be a scalar.");
        return;
    }
    if (PDIM(6) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }
    self.R_a = P(0, 0);
    self.k_v = P(1, 0);
    self.k_c = P(2, 0);
    self.i_d_max = PARAM(3);
    self.alpha_l = P(4, 0);
    /* Initial maximum active power (inf without the power limitation) */
    self.p_max = isnan(self.i_d_max) ? INFINITY : 1.5 * P(5, 0) * self.i_d_max;
    T_s = P(6, 0);

    self_init = self;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: the algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 1; k++) {
            OutputSignal(0, k) = 0.0;
        }
        for (int k = 0; k < 1; k++) {
            OutputSignal(1, k) = 0.0;
        }
        for (int k = 0; k < 2; k++) {
            OutputSignal(2, k) = 0.0;
        }
        return;
    }

    double fbk_u[FBK_WIDTH];
    for (int k = 0; k < FBK_WIDTH; k++) {
        fbk_u[k] = InputSignal(4, k);
    }
    gfm_feedbacks_unpack(fbk_u, &fbk);
    GFMReferences ref = {0};
    gfm_current_reference(&self, InputSignal(1, 0), InputSignal(2, 0), &fbk,
                          &ref);
    OutputSignal(0, 0) = ref.p_g;
    OutputSignal(1, 0) = ref.v_c;
    OutputSignal(2, 0) = creal(ref.i_c);
    OutputSignal(2, 1) = cimag(ref.i_c);
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        self = self_init;
        return;
    }

    /* Active-power limitation with the voltage reference ref.u_c */
    GFMReferences ref = {0};
    ref.u_c = complex_from(InputSignal(3, 0), InputSignal(3, 1));
    gfm_power_limit_update(&self, T_s, &ref, &fbk);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
