/*
 * sfun_fvc_reference_generator: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_fvc_reference_generator.c
 */

#define S_FUNCTION_NAME sfun_fvc_reference_generator
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export: a block of the control system. The
 * parameters come from its mask. */
#include "common.c"
#include "gradnet.c"
#include "sm_parameters.c"
#include "sm_control_loci.c"
#include "sm_flux_vector.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Check that a GradNet in the parameters i0, i0 + 1, ... (GRADNET_FIELDS) fits
 * in the arrays of the C port (in the start function only, returns on error) */
#define CHECK_GRADNET(i0) \
    do { \
        if ((int)P((i0), 0) > GRADNET_MAX_IN_DIM \
            || PDIM((i0) + 3) > GRADNET_MAX_EMBED_DIM) { \
            SetErrorMessage("GradNet too large: in_dim must be at most " \
                            "4 and embed_dim at most " \
                            "64."); \
            return; \
        } \
    } while (0)

/* Read a GradNet from the parameters i0, i0 + 1, ... (GRADNET_FIELDS) */
#define READ_GRADNET(net, i0) \
    do { \
        (net).in_dim = (int)P((i0), 0); \
        (net).mu_dim = (int)P((i0) + 1, 0); \
        (net).embed_dim = PDIM((i0) + 3); \
        for (int j_ = 0; j_ < (net).embed_dim; j_++) { \
            for (int k_ = 0; k_ < (net).in_dim; k_++) { \
                (net).W[j_][k_] = P((i0) + 2, j_ + (net).embed_dim * k_); \
            } \
            (net).b[j_] = P((i0) + 3, j_); \
        } \
        for (int k_ = 0; k_ < (net).in_dim; k_++) { \
            (net).mu_log[k_] = (k_ < (net).mu_dim) ? P((i0) + 4, k_) : 0.0; \
            (net).bias[k_] = P((i0) + 5, k_); \
        } \
        (net).activation = (GradNetActivation)(int)P((i0) + 6, 0); \
        (net).beta_log = P((i0) + 7, 0); \
        (net).p = (int)P((i0) + 8, 0); \
        (net).in_base = P((i0) + 9, 0); \
        (net).out_base = P((i0) + 10, 0); \
    } while (0)

static ReferenceGenerator self;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 1, 1};
static const int FEEDTHROUGH[] = {1, 1, 1};
static const int OUTPUT_WIDTHS[] = {2};
#define NUM_INPUTS 3
#define NUM_OUTPUTS 1
#define NUM_PARAMS 21

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, INHERITED_SAMPLE_TIME);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    if (PDIM(0) != 1) {
        SetErrorMessage("i_s_max must be a scalar.");
        return;
    }
    if (PDIM(2) != 1) {
        SetErrorMessage("psi_s_max must be a scalar.");
        return;
    }
    if (PDIM(3) != 1) {
        SetErrorMessage("k_u must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("k_mtpv must be a scalar.");
        return;
    }
    /* Machine model: SaturatedSynchronousMachinePars with a GradNet flux map,
     * or SynchronousMachinePars with constant inductances */
    SynchronousMachinePars par;
    if (PDIM(10) > 0) {
        GradNet flux_map;
        CHECK_GRADNET(10);
        READ_GRADNET(flux_map, 10);
        par = saturated_synchronous_machine_pars(P(5, 0), P(6, 0),
                                                 &flux_map);
    } else {
        if (PDIM(7) != 1 || PDIM(8) != 1 || PDIM(9) != 1) {
            SetErrorMessage("L_d, L_q, and psi_f needed without a flux map.");
            return;
        }
        par = synchronous_machine_pars(P(5, 0), P(6, 0), P(7, 0),
                                       P(8, 0), P(9, 0));
    }
    reference_gen_init(&self, &par, P(0, 0), PARAM(1),
                       P(2, 0), P(3, 0), P(4, 0));
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Flux and limited torque references (ref.psi_s, ref.tau_M) */
    double psi_s_ref, tau_M_ref;
    reference_gen_compute_flux_and_torque_refs(&self, InputSignal(0, 0),
        InputSignal(2, 0), InputSignal(1, 0), &psi_s_ref, &tau_M_ref);
    OutputSignal(0, 0) = psi_s_ref;
    OutputSignal(0, 1) = tau_M_ref;
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
