/*
 * sfun_fvc_flux_observer: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_fvc_flux_observer.c
 */

#define S_FUNCTION_NAME sfun_fvc_flux_observer
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export: a block of the control system. The
 * parameters come from its mask. */
#include "common.c"
#include "gradnet.c"
#include "sm_parameters.c"
#include "sm_control_loci.c"
#include "sm_flux_vector.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Check that a GradNet in the parameters i0, i0 + 1, ... (GRADNET_FIELDS) fits
 * in the arrays of the C port (in the start function only, returns on error) */
#define CHECK_GRADNET(i0) \
    do { \
        if ((int)P((i0), 0) > GRADNET_MAX_IN_DIM \
            || PDIM((i0) + 3) > GRADNET_MAX_EMBED_DIM) { \
            SetErrorMessage("GradNet too large: in_dim must be at most " \
                            "4 and embed_dim at most " \
                            "64."); \
            return; \
        } \
    } while (0)

/* Read a GradNet from the parameters i0, i0 + 1, ... (GRADNET_FIELDS) */
#define READ_GRADNET(net, i0) \
    do { \
        (net).in_dim = (int)P((i0), 0); \
        (net).mu_dim = (int)P((i0) + 1, 0); \
        (net).embed_dim = PDIM((i0) + 3); \
        for (int j_ = 0; j_ < (net).embed_dim; j_++) { \
            for (int k_ = 0; k_ < (net).in_dim; k_++) { \
                (net).W[j_][k_] = P((i0) + 2, j_ + (net).embed_dim * k_); \
            } \
            (net).b[j_] = P((i0) + 3, j_); \
        } \
        for (int k_ = 0; k_ < (net).in_dim; k_++) { \
            (net).mu_log[k_] = (k_ < (net).mu_dim) ? P((i0) + 4, k_) : 0.0; \
            (net).bias[k_] = P((i0) + 5, k_); \
        } \
        (net).activation = (GradNetActivation)(int)P((i0) + 6, 0); \
        (net).beta_log = P((i0) + 7, 0); \
        (net).p = (int)P((i0) + 8, 0); \
        (net).in_base = P((i0) + 9, 0); \
        (net).out_base = P((i0) + 10, 0); \
    } while (0)

static FluxObserver self;
static double T_s; /* Sampling period */
static double h;
static ObserverOutputs out;

/* Initial state, restored while the block is disabled */
static FluxObserver self_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 4, 2, 2, 1};
static const int FEEDTHROUGH[] = {1, 1, 1, 1, 1};
static const int OUTPUT_WIDTHS[] = {22};
#define NUM_INPUTS 5
#define NUM_OUTPUTS 1
#define NUM_PARAMS 21

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(4, 0) * ParamDim(4, 1) != 1
        || !(ParamRealData(4, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(4, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    if (PDIM(0) != 1) {
        SetErrorMessage("k_theta must be a scalar.");
        return;
    }
    if (PDIM(3) != 1) {
        SetErrorMessage("h must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }
    if (PDIM(1) != 2) {
        SetErrorMessage("k_o must be [k0 k1].");
        return;
    }
    if (PDIM(2) > 0 && P(2, 0) != 0.0) {
        SetErrorMessage("Only k_f = [] (zero) supported.");
        return;
    }
    /* Machine model: SaturatedSynchronousMachinePars with a GradNet flux map,
     * or SynchronousMachinePars with constant inductances */
    SynchronousMachinePars par;
    if (PDIM(10) > 0) {
        GradNet flux_map;
        CHECK_GRADNET(10);
        READ_GRADNET(flux_map, 10);
        par = saturated_synchronous_machine_pars(P(5, 0), P(6, 0),
                                                 &flux_map);
    } else {
        if (PDIM(7) != 1 || PDIM(8) != 1 || PDIM(9) != 1) {
            SetErrorMessage("L_d, L_q, and psi_f needed without a flux map.");
            return;
        }
        par = synchronous_machine_pars(P(5, 0), P(6, 0), P(7, 0),
                                       P(8, 0), P(9, 0));
    }
    double k_o[2] = {P(1, 0), P(1, 1)};
    if (isnan(k_o[0])) {
        /* Poles at zero speed at s = 0 and s = -2*sigma0 */
        IncrIndMat L_s0 = incr_ind_mat(&par, 0.0);
        k_o[0] = 0.25 * par.R_s * (1.0 / L_s0.L_dd + 1.0 / L_s0.L_qq);
    }
    flux_observer_init(&self, par, P(0, 0), k_o);
    T_s = P(4, 0);
    h = P(3, 0);

    self_init = self;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: the algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 22; k++) {
            OutputSignal(0, k) = 0.0;
        }
        return;
    }

    double meas_u[MEAS_WIDTH];
    for (int k = 0; k < MEAS_WIDTH; k++) {
        meas_u[k] = InputSignal(1, k);
    }
    Measurements meas;
    measurements_unpack(meas_u, &meas);
    double complex u_s_ab = complex_from(InputSignal(2, 0), InputSignal(2, 1));
    double complex u_s_zoh_ab = complex_from(InputSignal(3, 0), InputSignal(3, 1));
    double w_M = InputSignal(4, 0);
    if (h == 0.0) {
        flux_observer_compute_output(&self, u_s_ab, u_s_zoh_ab, meas.i_c_ab,
                                     w_M, 0.0, 0.0, &out);
    } else {
        /* Position error from the measured rotor angle (position_error) */
        double n_p = self.par.n_p;
        double eps = wrap(n_p * meas.theta_M - self.theta_m) / n_p;
        flux_observer_compute_output(&self, u_s_ab, u_s_zoh_ab, meas.i_c_ab,
                                     w_M, eps, h, &out);
    }
    double y[FBK_WIDTH];
    observer_outputs_pack(&out, y);
    for (int k = 0; k < FBK_WIDTH; k++) {
        OutputSignal(0, k) = y[k];
    }
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        self = self_init;
        return;
    }

    flux_observer_update(&self, T_s, &out);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
