/*
 * sfun_gradnet_machine: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_gradnet_machine.c
 */

#define S_FUNCTION_NAME sfun_gradnet_machine
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export.plecs.sm. The magnetic model is in the
 * included C files. The parameters come from the initialization
 * commands. */
#include "common.c"
#include "gradnet.c"
#include "sm_machine.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Check that a GradNet in the parameters i0, i0 + 1, ... (GRADNET_FIELDS) fits
 * in the arrays of the C port (in the start function only, returns on error) */
#define CHECK_GRADNET(i0) \
    do { \
        if ((int)P((i0), 0) > GRADNET_MAX_IN_DIM \
            || PDIM((i0) + 3) > GRADNET_MAX_EMBED_DIM) { \
            SetErrorMessage("GradNet too large: in_dim must be at most " \
                            "4 and embed_dim at most " \
                            "64."); \
            return; \
        } \
    } while (0)

/* Read a GradNet from the parameters i0, i0 + 1, ... (GRADNET_FIELDS) */
#define READ_GRADNET(net, i0) \
    do { \
        (net).in_dim = (int)P((i0), 0); \
        (net).mu_dim = (int)P((i0) + 1, 0); \
        (net).embed_dim = PDIM((i0) + 3); \
        for (int j_ = 0; j_ < (net).embed_dim; j_++) { \
            for (int k_ = 0; k_ < (net).in_dim; k_++) { \
                (net).W[j_][k_] = P((i0) + 2, j_ + (net).embed_dim * k_); \
            } \
            (net).b[j_] = P((i0) + 3, j_); \
        } \
        for (int k_ = 0; k_ < (net).in_dim; k_++) { \
            (net).mu_log[k_] = (k_ < (net).mu_dim) ? P((i0) + 4, k_) : 0.0; \
            (net).bias[k_] = P((i0) + 5, k_); \
        } \
        (net).activation = (GradNetActivation)(int)P((i0) + 6, 0); \
        (net).beta_log = P((i0) + 7, 0); \
        (net).p = (int)P((i0) + 8, 0); \
        (net).in_base = P((i0) + 9, 0); \
        (net).out_base = P((i0) + 10, 0); \
    } while (0)

static SpatialSaturatedSynchronousMachinePars par;

/* Stator flux linkage in rotor coordinates */
#define PSI_D ContState(0)
#define PSI_Q ContState(1)

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {2, 1, 1};
static const int FEEDTHROUGH[] = {0, 1, 1};
static const int OUTPUT_WIDTHS[] = {2, 3, 1, 1, 1};
#define NUM_INPUTS 3
#define NUM_OUTPUTS 5
#define NUM_PARAMS 14

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 2);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, CONTINUOUS_SAMPLE_TIME);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    GradNet current_map;
    CHECK_GRADNET(3);
    READ_GRADNET(current_map, 3);
    par = spatial_saturated_synchronous_machine_pars(
        P(0, 0), P(1, 0), &current_map, (int)P(2, 0));
    if (isnan(par.psi_f)) {
        SetErrorMessage("The PM-flux linkage cannot be solved from the current "
                        "map.");
        return;
    }
    PSI_D = par.psi_f; /* Initial states as in motulator */
    PSI_Q = 0.0;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Inputs: voltages -u_ac and -u_bc, rotor angle, and rotor speed */
    double theta_M = InputSignal(1, 0), w_M = InputSignal(2, 0);
    double complex i_s_dq;
    double tau_M;
    double theta_m = par.n_p * theta_M;
    machine_magnetic_map(&par, PSI_D + I * PSI_Q, theta_m, &i_s_dq, &tau_M);
    double i_s_abc[3];
    complex2abc(i_s_dq * cexp(I * theta_m), i_s_abc);
    /* Phase currents a and b to the current sources, phase c is the return */
    OutputSignal(0, 0) = i_s_abc[0];
    OutputSignal(0, 1) = i_s_abc[1];
    for (int k = 0; k < 3; k++) {
        OutputSignal(1, k) = i_s_abc[k];
    }
    OutputSignal(2, 0) = tau_M;
    OutputSignal(3, 0) = w_M;
    OutputSignal(4, 0) = theta_M;
}

#define MDL_DERIVATIVES
static void mdlDerivatives(SimStruct *S)
{
    /* Stator voltage from the line voltages u_ac and u_bc, which are the
     * negated voltages of the current sources (zero sequence is irrelevant) */
    double complex u_s_ab =
        -2.0 / 3.0 * (InputSignal(0, 0) + cexp(I * 2.0 * M_PI / 3.0) * InputSignal(0, 1));
    double complex d_psi_s_dq = machine_flux_rhs(
        &par, u_s_ab, PSI_D + I * PSI_Q, InputSignal(1, 0), InputSignal(2, 0));
    ContDeriv(0) = creal(d_psi_s_dq);
    ContDeriv(1) = cimag(d_psi_s_dq);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
