"""
S-functions generated from the C-Script code of the PLECS models.

The code sections of a C-Script block (e.g., `CBlock.code` of the blocks of the
control systems) are wrapped in a Level-2 C MEX S-function, which defines the
C-Script macros used in the code with the Simulink API. The S-function thus runs the
same code as the C-Script block of the PLECS model, with the same ports,
parameters, sample time, and continuous states.

"""

from dataclasses import dataclass, field
from pathlib import Path

from motulator_export.plecs import sm
from motulator_export.plecs._common import C_DIR
from motulator_export.plecs._netlist import CBlock

# C-Script macros in terms of the Simulink API (the SimStruct is S in the callbacks)
MACROS = """\
#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \\
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \\
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])
"""


@dataclass
class SFunction:
    """Level-2 C MEX S-function wrapping the code sections of a C-Script block."""

    name: str  # Name of the S-function and of its source file (without .c)
    code: dict[str, str]  # Code sections of the C-Script
    input_widths: list[int]
    output_widths: list[int]
    params: list[str]  # Parameter expressions, evaluated in the mask workspace
    sample_time: int | None  # Index of the sample-time parameter, None = continuous
    num_cont_states: int = 0
    feedthrough: list[int] = field(default_factory=list)  # Defaults to all inputs
    inherited: bool = False  # Inherited sample time (sample_time is None)

    def source(self) -> str:
        """C source of the S-function."""
        code = {k: v.replace(f"{C_DIR}/", "") for k, v in self.code.items()}
        feedthrough = self.feedthrough or [1] * len(self.input_widths)
        n_params = len(self.params)
        if self.sample_time is None:
            ts = "INHERITED_SAMPLE_TIME" if self.inherited else "CONTINUOUS_SAMPLE_TIME"
            sample_time = (
                f"    ssSetSampleTime(S, 0, {ts});\n    ssSetOffsetTime(S, 0, 0.0);\n"
            )
            ts_check = ""
        else:
            ts = self.sample_time
            sample_time = (
                f"    ssSetSampleTime(S, 0, ParamRealData({ts}, 0));\n"
                "    ssSetOffsetTime(S, 0, 0.0);\n"
            )
            ts_check = (
                f"    if (ParamDim({ts}, 0) * ParamDim({ts}, 1) != 1\n"
                f"        || !(ParamRealData({ts}, 0) > 0.0)) {{\n"
                '        SetErrorMessage("The sampling period must be a positive '
                'scalar.");\n'
                "        return;\n"
                "    }\n"
            )
        callbacks = _callback("MDL_START", "mdlStart(SimStruct *S)", code["StartFcn"])
        callbacks += _callback(
            None,
            "mdlOutputs(SimStruct *S, int_T tid)",
            "UNUSED_ARG(tid);\n" + code["OutputFcn"],
        )
        if code.get("UpdateFcn"):
            callbacks += _callback(
                "MDL_UPDATE",
                "mdlUpdate(SimStruct *S, int_T tid)",
                "UNUSED_ARG(tid);\n" + code["UpdateFcn"],
            )
        if code.get("DerivativeFcn"):
            callbacks += _callback(
                "MDL_DERIVATIVES", "mdlDerivatives(SimStruct *S)", code["DerivativeFcn"]
            )
        callbacks += _callback(None, "mdlTerminate(SimStruct *S)", "UNUSED_ARG(S);\n")
        return (
            "/*\n"
            f" * {self.name}: Level-2 C MEX S-function generated by motulator_export\n"
            " * from the C-Script code of the PLECS model. The C-Script macros are\n"
            " * defined with the Simulink API. The state of the code is in static\n"
            " * variables, so a model can contain one instance of the block.\n"
            " *\n"
            " * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):\n"
            f" *     mex -I<motulator_export/c> {self.name}.c\n"
            " */\n"
            "\n"
            f"#define S_FUNCTION_NAME {self.name}\n"
            "#define S_FUNCTION_LEVEL 2\n"
            "\n"
            '#include "simstruc.h"\n'
            "\n" + MACROS + "\n"
            "/* Declarations of the C-Script (after simstruc.h, since complex.h\n"
            " * defines the macro I) */\n" + code.get("Declarations", "") + "\n"
            "/* Ports and parameters of the C-Script */\n"
            f"static const int INPUT_WIDTHS[] = {_c_list(self.input_widths)};\n"
            f"static const int FEEDTHROUGH[] = {_c_list(feedthrough)};\n"
            f"static const int OUTPUT_WIDTHS[] = {_c_list(self.output_widths)};\n"
            f"#define NUM_INPUTS {len(self.input_widths)}\n"
            f"#define NUM_OUTPUTS {len(self.output_widths)}\n"
            f"#define NUM_PARAMS {n_params}\n"
            "\n"
            "static void mdlInitializeSizes(SimStruct *S)\n"
            "{\n"
            "    ssSetNumSFcnParams(S, NUM_PARAMS);\n"
            f"    ssSetNumContStates(S, {self.num_cont_states});\n"
            "    ssSetNumDiscStates(S, 0);\n"
            "    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {\n"
            "        return;\n"
            "    }\n"
            "    for (int k = 0; k < NUM_INPUTS; k++) {\n"
            "        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);\n"
            "        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);\n"
            "        ssSetInputPortRequiredContiguous(S, k, 1);\n"
            "    }\n"
            "    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {\n"
            "        return;\n"
            "    }\n"
            "    for (int k = 0; k < NUM_OUTPUTS; k++) {\n"
            "        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);\n"
            "    }\n"
            "    ssSetNumSampleTimes(S, 1);\n"
            "    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);\n"
            "#if defined(MATLAB_MEX_FILE)\n"
            "    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {\n"
            "        return; /* Reported by Simulink */\n"
            "    }\n"
            "    for (int k = 0; k < NUM_PARAMS; k++) {\n"
            "        const mxArray *p = ssGetSFcnParam(S, k);\n"
            "        if (!mxIsDouble(p) || mxIsComplex(p)) {\n"
            "            SetErrorMessage(\n"
            '                "The parameters must be real double arrays.");\n'
            "            return;\n"
            "        }\n"
            "        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);\n"
            "    }\n" + ts_check + "#endif\n"
            "}\n"
            "\n"
            "static void mdlInitializeSampleTimes(SimStruct *S)\n"
            "{\n" + sample_time + "}\n" + callbacks + "\n"
            "#ifdef MATLAB_MEX_FILE\n"
            '#include "simulink.c"\n'
            "#else\n"
            '#include "cg_sfun.h"\n'
            "#endif\n"
        )

    def write(self, folder: str | Path) -> Path:
        """Write the source of the S-function in the folder."""
        path = Path(folder) / f"{self.name}.c"
        path.write_text(self.source(), encoding="utf-8")
        return path


def _callback(define: str | None, signature: str, body: str) -> str:
    """S-function callback with the indented body."""
    lines = "".join(f"    {line}\n" if line else "\n" for line in body.splitlines())
    return (
        "\n"
        + (f"#define {define}\n" if define else "")
        + f"static void {signature}\n{{\n{lines}}}\n"
    )


def _c_list(values: list[int]) -> str:
    """C initializer list."""
    return "{" + ", ".join(str(v) for v in values) + "}"


def block_sfunction(block: CBlock) -> SFunction:
    """S-function of a C block of a control system (see `plecs._netlist`)."""
    return SFunction(
        name=block.sfunction,
        code=block.code,
        input_widths=[p.width for p in block.inputs],
        output_widths=[p.width for p in block.outputs],
        params=[f"double({p})" for p in block.params],
        sample_time=(
            None if block.sample_time is None else block.params.index(block.sample_time)
        ),
        feedthrough=block.feedthrough or [],
        inherited=block.sample_time is None,
    )


def gradnet_machine_sfunction() -> SFunction:
    """
    S-function of the synchronous machine with a GradNet current map.

    The code is that of the C-Script block of the PLECS model. The inputs are the
    negated line-to-line voltages -u_ac and -u_bc, the rotor angle, and the rotor
    speed, and the outputs are the phase currents a and b, the phase currents, the
    torque, the speed, and the angle. The stator flux linkage is the continuous
    state. The parameters are in the struct `machine` of the initialization script.

    """
    params = ["machine.n_p", "machine.R_s", "machine.k"]
    params += [f"machine.current_map.{f}" for f in sm.GRADNET_FIELDS]
    return SFunction(
        name="sfun_gradnet_machine",
        code=sm._machine_cscript_code(),
        input_widths=[2, 1, 1],
        output_widths=[2, 3, 1, 1, 1],
        params=[f"double({p})" for p in params],
        sample_time=None,
        num_cont_states=2,
        feedthrough=[0, 1, 1],
    )
