function slx = new_model(s)
%NEW_MODEL Create the model s.name with its workspace and solver settings.
%   The workspace of the model is the MATLAB code s.init (the parameters of the
%   system model). The solver is as in the PLECS models: Dormand-Prince with the
%   relative tolerance of 1e-6 and the maximum step s.T_s. The outputs are saved as
%   arrays for the comparison with motulator. Unconnected ports and lines are
%   errors, so that the builders cannot leave them. A previous model in s.folder
%   is closed and deleted, since it would shadow the new one. Returns the path of
%   the model.
name = s.name;
if bdIsLoaded(name)
    close_system(name, 0);
end
slx = fullfile(s.folder, [name '.slx']);
if isfile(slx)
    delete(slx);
end
addpath(s.folder);
new_system(name);
ws = get_param(name, 'ModelWorkspace');
ws.DataSource = 'MATLAB Code';
ws.MATLABCode = s.init;
ws.reload;
set_param(name, ...
    'Solver', 'ode45', ...
    'MaxStep', blocks.num(s.T_s), ...
    'RelTol', '1e-6', ...
    'AbsTol', 'auto', ...
    'StopTime', blocks.num(s.t_stop), ...
    'SaveTime', 'on', ...
    'SaveOutput', 'on', ...
    'SaveFormat', 'Array', ...
    'LimitDataPoints', 'off', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'UnconnectedInputMsg', 'error', ...
    'UnconnectedOutputMsg', 'error', ...
    'UnconnectedLineMsg', 'error', ...
    'InitFcn', 'addpath(fileparts(get_param(bdroot, ''FileName'')))');
end
